package net.codinux.kotlin.text

import net.codinux.collections.immutableMapOf

object ICU {

    val CurrencyIsoCodeToCurrencySymbol = immutableMapOf(
        "AED" to "د.إ.‏",
        "AED" to "AED",
        "AFN" to "؋",
        "ALL" to "Lekë",
        "AMD" to "֏",
        "ANG" to "NAf.",
        "AOA" to "Kz",
        "ARS" to "$",
        "AUD" to "$",
        "AWG" to "Afl.",
        "AZN" to "₼",
        "BAM" to "КМ",
        "BAM" to "KM",
        "BBD" to "$",
        "BDT" to "৳",
        "BGN" to "лв.",
        "BHD" to "د.ب.‏",
        "BIF" to "FBu",
        "BMD" to "$",
        "BND" to "$",
        "BOB" to "Bs",
        "BRL" to "R$",
        "BSD" to "$",
        "BTN" to "Nu.",
        "BWP" to "P",
        "BYN" to "Br",
        "BZD" to "$",
        "CAD" to "$",
        "CDF" to "FC",
        "CHF" to "CHF",
        "CLP" to "$",
        "CNY" to "¥",
        "CNY" to "￥",
        "COP" to "$",
        "CRC" to "₡",
        "CUP" to "$",
        "CVE" to "​",
        "CZK" to "Kč",
        "DJF" to "Fdj",
        "DKK" to "kr.",
        "DKK" to "kr",
        "DOP" to "RD$",
        "DZD" to "د.ج.‏",
        "DZD" to "DA",
        "EGP" to "ج.م.‏",
        "ERN" to "Nfk",
        "ETB" to "ብር",
        "ETB" to "Br",
        "EUR" to "€",
        "FJD" to "$",
        "FKP" to "£",
        "GBP" to "£",
        "GEL" to "₾",
        "GHS" to "GH₵",
        "GIP" to "£",
        "GMD" to "D",
        "GNF" to "FG",
        "GTQ" to "Q",
        "GYD" to "$",
        "HKD" to "HK$",
        "HNL" to "L",
        "HTG" to "G",
        "HUF" to "Ft",
        "IDR" to "Rp",
        "ILS" to "₪",
        "INR" to "₹",
        "IQD" to "د.ع.‏",
        "IRR" to "IRR",
        "IRR" to "ریال",
        "ISK" to "kr.",
        "JMD" to "$",
        "JOD" to "د.أ.‏",
        "JPY" to "￥",
        "KES" to "Ksh",
        "KGS" to "сом",
        "KHR" to "៛",
        "KMF" to "CF",
        "KPW" to "KPW",
        "KRW" to "₩",
        "KWD" to "د.ك.‏",
        "KYD" to "$",
        "KZT" to "₸",
        "LAK" to "₭",
        "LBP" to "ل.ل.‏",
        "LKR" to "රු.",
        "LKR" to "Rs.",
        "LRD" to "$",
        "LYD" to "د.ل.‏",
        "MAD" to "د.م.‏",
        "MAD" to "MAD",
        "MDL" to "L",
        "MGA" to "Ar",
        "MKD" to "ден.",
        "MKD" to "den",
        "MMK" to "K",
        "MNT" to "₮",
        "MOP" to "MOP$",
        "MRU" to "أ.م.",
        "MRU" to "UM",
        "MUR" to "Rs",
        "MVR" to "Rf",
        "MWK" to "MK",
        "MXN" to "$",
        "MYR" to "RM",
        "MZN" to "MTn",
        "NAD" to "$",
        "NGN" to "₦",
        "NIO" to "C$",
        "NOK" to "kr",
        "NPR" to "नेरू",
        "NZD" to "$",
        "OMR" to "ر.ع.‏",
        "PAB" to "B/.",
        "PEN" to "S/",
        "PGK" to "K",
        "PHP" to "₱",
        "PKR" to "Rs",
        "PKR" to "ر",
        "PLN" to "zł",
        "PYG" to "Gs.",
        "QAR" to "ر.ق.‏",
        "RON" to "RON",
        "RSD" to "RSD",
        "RUB" to "₽",
        "RWF" to "RF",
        "SAR" to "ر.س.‏",
        "SBD" to "$",
        "SCR" to "SR",
        "SDG" to "ج.س.",
        "SDG" to "SDG",
        "SEK" to "kr",
        "SGD" to "$",
        "SHP" to "£",
        "SLE" to "Le",
        "SOS" to "S",
        "SRD" to "$",
        "SSP" to "£",
        "STN" to "Db",
        "SYP" to "ل.س.‏",
        "SYP" to "LS",
        "SZL" to "E",
        "THB" to "฿",
        "TJS" to "сом.",
        "TMT" to "TMT",
        "TND" to "د.ت.‏",
        "TND" to "DT",
        "TOP" to "T$",
        "TRY" to "₺",
        "TTD" to "$",
        "TWD" to "$",
        "TZS" to "TSh",
        "UAH" to "₴",
        "UGX" to "USh",
        "USD" to "$",
        "USD" to "US$",
        "UYU" to "$",
        "UZS" to "сўм",
        "UZS" to "soʻm",
        "VES" to "Bs.S",
        "VND" to "₫",
        "VUV" to "VT",
        "WST" to "WS$",
        "XAF" to "FCFA",
        "XAF" to "𞤊𞤅𞤊𞤀",
        "XCD" to "$",
        "XOF" to "F CFA",
        "XOF" to "𞤅𞤊𞤀",
        "XPF" to "FCFP",
        "XXX" to "¤",
        "YER" to "ر.ي.‏",
        "ZAR" to "R",
        "ZMW" to "K"
    )

    val LocaleToCurrencyIsoCode = immutableMapOf(
        "af-NA" to "NAD",
        "af-ZA" to "ZAR",
        "agq-CM" to "XAF",
        "ak-GH" to "GHS",
        "am-ET" to "ETB",
        "ar-001" to "XXX",
        "ar-AE" to "AED",
        "ar-BH" to "BHD",
        "ar-DJ" to "DJF",
        "ar-DZ" to "DZD",
        "ar-EG" to "EGP",
        "ar-EH" to "MAD",
        "ar-ER" to "ERN",
        "ar-IL" to "ILS",
        "ar-IQ" to "IQD",
        "ar-JO" to "JOD",
        "ar-KM" to "KMF",
        "ar-KW" to "KWD",
        "ar-LB" to "LBP",
        "ar-LY" to "LYD",
        "ar-MA" to "MAD",
        "ar-MR" to "MRU",
        "ar-OM" to "OMR",
        "ar-PS" to "ILS",
        "ar-QA" to "QAR",
        "ar-SA" to "SAR",
        "ar-SD" to "SDG",
        "ar-SO" to "SOS",
        "ar-SS" to "SSP",
        "ar-SY" to "SYP",
        "ar-TD" to "XAF",
        "ar-TN" to "TND",
        "ar-YE" to "YER",
        "as-IN" to "INR",
        "asa-TZ" to "TZS",
        "ast-ES" to "EUR",
        "az-Cyrl-AZ" to "AZN",
        "az-Latn-AZ" to "AZN",
        "bas-CM" to "XAF",
        "be-BY" to "BYN",
        "bem-ZM" to "ZMW",
        "bez-TZ" to "TZS",
        "bg-BG" to "BGN",
        "bgc-IN" to "INR",
        "bho-IN" to "INR",
        "bm-ML" to "XOF",
        "bn-BD" to "BDT",
        "bn-IN" to "INR",
        "bo-CN" to "CNY",
        "bo-IN" to "INR",
        "br-FR" to "EUR",
        "brx-IN" to "INR",
        "bs-Cyrl-BA" to "BAM",
        "bs-Latn-BA" to "BAM",
        "ca-AD" to "EUR",
        "ca-ES" to "EUR",
        "ca-FR" to "EUR",
        "ca-IT" to "EUR",
        "ccp-BD" to "BDT",
        "ccp-IN" to "INR",
        "ce-RU" to "RUB",
        "ceb-PH" to "PHP",
        "cgg-UG" to "UGX",
        "chr-US" to "USD",
        "ckb-IQ" to "IQD",
        "ckb-IR" to "IRR",
        "cs-CZ" to "CZK",
        "cv-RU" to "RUB",
        "cy-GB" to "GBP",
        "da-DK" to "DKK",
        "da-GL" to "DKK",
        "dav-KE" to "KES",
        "de-AT" to "EUR",
        "de-BE" to "EUR",
        "de-CH" to "CHF",
        "de-DE" to "EUR",
        "de-IT" to "EUR",
        "de-LI" to "CHF",
        "de-LU" to "EUR",
        "dje-NE" to "XOF",
        "doi-IN" to "INR",
        "dsb-DE" to "EUR",
        "dua-CM" to "XAF",
        "dyo-SN" to "XOF",
        "dz-BT" to "BTN",
        "ebu-KE" to "KES",
        "ee-GH" to "GHS",
        "ee-TG" to "XOF",
        "el-CY" to "EUR",
        "el-GR" to "EUR",
        "en-001" to "XXX",
        "en-150" to "XXX",
        "en-AE" to "AED",
        "en-AG" to "XCD",
        "en-AI" to "XCD",
        "en-AS" to "USD",
        "en-AT" to "EUR",
        "en-AU" to "AUD",
        "en-BB" to "BBD",
        "en-BE" to "EUR",
        "en-BI" to "BIF",
        "en-BM" to "BMD",
        "en-BS" to "BSD",
        "en-BW" to "BWP",
        "en-BZ" to "BZD",
        "en-CA" to "CAD",
        "en-CC" to "AUD",
        "en-CH" to "CHF",
        "en-CK" to "NZD",
        "en-CM" to "XAF",
        "en-CX" to "AUD",
        "en-CY" to "EUR",
        "en-DE" to "EUR",
        "en-DG" to "USD",
        "en-DK" to "DKK",
        "en-DM" to "XCD",
        "en-ER" to "ERN",
        "en-FI" to "EUR",
        "en-FJ" to "FJD",
        "en-FK" to "FKP",
        "en-FM" to "USD",
        "en-GB" to "GBP",
        "en-GD" to "XCD",
        "en-GG" to "GBP",
        "en-GH" to "GHS",
        "en-GI" to "GIP",
        "en-GM" to "GMD",
        "en-GU" to "USD",
        "en-GY" to "GYD",
        "en-HK" to "HKD",
        "en-IE" to "EUR",
        "en-IL" to "ILS",
        "en-IM" to "GBP",
        "en-IN" to "INR",
        "en-IO" to "USD",
        "en-JE" to "GBP",
        "en-JM" to "JMD",
        "en-KE" to "KES",
        "en-KI" to "AUD",
        "en-KN" to "XCD",
        "en-KY" to "KYD",
        "en-LC" to "XCD",
        "en-LR" to "LRD",
        "en-LS" to "ZAR",
        "en-MG" to "MGA",
        "en-MH" to "USD",
        "en-MO" to "MOP",
        "en-MP" to "USD",
        "en-MS" to "XCD",
        "en-MT" to "EUR",
        "en-MU" to "MUR",
        "en-MV" to "MVR",
        "en-MW" to "MWK",
        "en-MY" to "MYR",
        "en-NA" to "NAD",
        "en-NF" to "AUD",
        "en-NG" to "NGN",
        "en-NL" to "EUR",
        "en-NR" to "AUD",
        "en-NU" to "NZD",
        "en-NZ" to "NZD",
        "en-PG" to "PGK",
        "en-PH" to "PHP",
        "en-PK" to "PKR",
        "en-PN" to "NZD",
        "en-PR" to "USD",
        "en-PW" to "USD",
        "en-RW" to "RWF",
        "en-SB" to "SBD",
        "en-SC" to "SCR",
        "en-SD" to "SDG",
        "en-SE" to "SEK",
        "en-SG" to "SGD",
        "en-SH" to "SHP",
        "en-SI" to "EUR",
        "en-SL" to "SLE",
        "en-SS" to "SSP",
        "en-SX" to "ANG",
        "en-SZ" to "SZL",
        "en-TC" to "USD",
        "en-TK" to "NZD",
        "en-TO" to "TOP",
        "en-TT" to "TTD",
        "en-TV" to "AUD",
        "en-TZ" to "TZS",
        "en-UG" to "UGX",
        "en-UM" to "USD",
        "en-US" to "USD",
        "en-US-u-va-posix" to "USD",
        "en-VC" to "XCD",
        "en-VG" to "USD",
        "en-VI" to "USD",
        "en-VU" to "VUV",
        "en-WS" to "WST",
        "en-ZA" to "ZAR",
        "en-ZM" to "ZMW",
        "en-ZW" to "USD",
        "eo-001" to "XXX",
        "es-419" to "XXX",
        "es-AR" to "ARS",
        "es-BO" to "BOB",
        "es-BR" to "BRL",
        "es-BZ" to "BZD",
        "es-CL" to "CLP",
        "es-CO" to "COP",
        "es-CR" to "CRC",
        "es-CU" to "CUP",
        "es-DO" to "DOP",
        "es-EA" to "EUR",
        "es-EC" to "USD",
        "es-ES" to "EUR",
        "es-GQ" to "XAF",
        "es-GT" to "GTQ",
        "es-HN" to "HNL",
        "es-IC" to "EUR",
        "es-MX" to "MXN",
        "es-NI" to "NIO",
        "es-PA" to "PAB",
        "es-PE" to "PEN",
        "es-PH" to "PHP",
        "es-PR" to "USD",
        "es-PY" to "PYG",
        "es-SV" to "USD",
        "es-US" to "USD",
        "es-UY" to "UYU",
        "es-VE" to "VES",
        "et-EE" to "EUR",
        "eu-ES" to "EUR",
        "ewo-CM" to "XAF",
        "fa-AF" to "AFN",
        "fa-IR" to "IRR",
        "ff-Adlm-BF" to "XOF",
        "ff-Adlm-CM" to "XAF",
        "ff-Adlm-GH" to "GHS",
        "ff-Adlm-GM" to "GMD",
        "ff-Adlm-GN" to "GNF",
        "ff-Adlm-GW" to "XOF",
        "ff-Adlm-LR" to "LRD",
        "ff-Adlm-MR" to "MRU",
        "ff-Adlm-NE" to "XOF",
        "ff-Adlm-NG" to "NGN",
        "ff-Adlm-SL" to "SLE",
        "ff-Adlm-SN" to "XOF",
        "ff-Latn-BF" to "XOF",
        "ff-Latn-CM" to "XAF",
        "ff-Latn-GH" to "GHS",
        "ff-Latn-GM" to "GMD",
        "ff-Latn-GN" to "GNF",
        "ff-Latn-GW" to "XOF",
        "ff-Latn-LR" to "LRD",
        "ff-Latn-MR" to "MRU",
        "ff-Latn-NE" to "XOF",
        "ff-Latn-NG" to "NGN",
        "ff-Latn-SL" to "SLE",
        "ff-Latn-SN" to "XOF",
        "fi-FI" to "EUR",
        "fil-PH" to "PHP",
        "fo-DK" to "DKK",
        "fo-FO" to "DKK",
        "fr-BE" to "EUR",
        "fr-BF" to "XOF",
        "fr-BI" to "BIF",
        "fr-BJ" to "XOF",
        "fr-BL" to "EUR",
        "fr-CA" to "CAD",
        "fr-CD" to "CDF",
        "fr-CF" to "XAF",
        "fr-CG" to "XAF",
        "fr-CH" to "CHF",
        "fr-CI" to "XOF",
        "fr-CM" to "XAF",
        "fr-DJ" to "DJF",
        "fr-DZ" to "DZD",
        "fr-FR" to "EUR",
        "fr-GA" to "XAF",
        "fr-GF" to "EUR",
        "fr-GN" to "GNF",
        "fr-GP" to "EUR",
        "fr-GQ" to "XAF",
        "fr-HT" to "HTG",
        "fr-KM" to "KMF",
        "fr-LU" to "EUR",
        "fr-MA" to "MAD",
        "fr-MC" to "EUR",
        "fr-MF" to "EUR",
        "fr-MG" to "MGA",
        "fr-ML" to "XOF",
        "fr-MQ" to "EUR",
        "fr-MR" to "MRU",
        "fr-MU" to "MUR",
        "fr-NC" to "XPF",
        "fr-NE" to "XOF",
        "fr-PF" to "XPF",
        "fr-PM" to "EUR",
        "fr-RE" to "EUR",
        "fr-RW" to "RWF",
        "fr-SC" to "SCR",
        "fr-SN" to "XOF",
        "fr-SY" to "SYP",
        "fr-TD" to "XAF",
        "fr-TG" to "XOF",
        "fr-TN" to "TND",
        "fr-VU" to "VUV",
        "fr-WF" to "XPF",
        "fr-YT" to "EUR",
        "fur-IT" to "EUR",
        "fy-NL" to "EUR",
        "ga-GB" to "GBP",
        "ga-IE" to "EUR",
        "gd-GB" to "GBP",
        "gl-ES" to "EUR",
        "gsw-CH" to "CHF",
        "gsw-FR" to "EUR",
        "gsw-LI" to "CHF",
        "gu-IN" to "INR",
        "guz-KE" to "KES",
        "gv-IM" to "GBP",
        "ha-GH" to "GHS",
        "ha-NE" to "XOF",
        "ha-NG" to "NGN",
        "haw-US" to "USD",
        "he-IL" to "ILS",
        "hi-IN" to "INR",
        "hi-Latn-IN" to "INR",
        "hr-BA" to "BAM",
        "hr-HR" to "EUR",
        "hsb-DE" to "EUR",
        "hu-HU" to "HUF",
        "hy-AM" to "AMD",
        "ia-001" to "XXX",
        "id-ID" to "IDR",
        "ig-NG" to "NGN",
        "ii-CN" to "CNY",
        "is-IS" to "ISK",
        "it-CH" to "CHF",
        "it-IT" to "EUR",
        "it-SM" to "EUR",
        "it-VA" to "EUR",
        "ja-JP" to "JPY",
        "jgo-CM" to "XAF",
        "jmc-TZ" to "TZS",
        "jv-ID" to "IDR",
        "ka-GE" to "GEL",
        "kab-DZ" to "DZD",
        "kam-KE" to "KES",
        "kde-TZ" to "TZS",
        "kea-CV" to "CVE",
        "kgp-BR" to "BRL",
        "khq-ML" to "XOF",
        "ki-KE" to "KES",
        "kk-KZ" to "KZT",
        "kkj-CM" to "XAF",
        "kl-GL" to "DKK",
        "kln-KE" to "KES",
        "km-KH" to "KHR",
        "kn-IN" to "INR",
        "ko-KP" to "KPW",
        "ko-KR" to "KRW",
        "kok-IN" to "INR",
        "ks-Arab-IN" to "INR",
        "ks-Deva-IN" to "INR",
        "ksb-TZ" to "TZS",
        "ksf-CM" to "XAF",
        "ksh-DE" to "EUR",
        "ku-TR" to "TRY",
        "kw-GB" to "GBP",
        "ky-KG" to "KGS",
        "lag-TZ" to "TZS",
        "lb-LU" to "EUR",
        "lg-UG" to "UGX",
        "lkt-US" to "USD",
        "ln-AO" to "AOA",
        "ln-CD" to "CDF",
        "ln-CF" to "XAF",
        "ln-CG" to "XAF",
        "lo-LA" to "LAK",
        "lrc-IQ" to "IQD",
        "lrc-IR" to "IRR",
        "lt-LT" to "EUR",
        "lu-CD" to "CDF",
        "luo-KE" to "KES",
        "luy-KE" to "KES",
        "lv-LV" to "EUR",
        "mai-IN" to "INR",
        "mas-KE" to "KES",
        "mas-TZ" to "TZS",
        "mer-KE" to "KES",
        "mfe-MU" to "MUR",
        "mg-MG" to "MGA",
        "mgh-MZ" to "MZN",
        "mgo-CM" to "XAF",
        "mi-NZ" to "NZD",
        "mk-MK" to "MKD",
        "ml-IN" to "INR",
        "mn-MN" to "MNT",
        "mni-Beng-IN" to "INR",
        "mr-IN" to "INR",
        "ms-BN" to "BND",
        "ms-ID" to "IDR",
        "ms-MY" to "MYR",
        "ms-SG" to "SGD",
        "mt-MT" to "EUR",
        "mua-CM" to "XAF",
        "my-MM" to "MMK",
        "mzn-IR" to "IRR",
        "naq-NA" to "NAD",
        "nb-NO" to "NOK",
        "nb-SJ" to "NOK",
        "nd-ZW" to "USD",
        "ne-IN" to "INR",
        "ne-NP" to "NPR",
        "nl-AW" to "AWG",
        "nl-BE" to "EUR",
        "nl-BQ" to "USD",
        "nl-CW" to "ANG",
        "nl-NL" to "EUR",
        "nl-SR" to "SRD",
        "nl-SX" to "ANG",
        "nmg-CM" to "XAF",
        "nn-NO" to "NOK",
        "nnh-CM" to "XAF",
        "nus-SS" to "SSP",
        "nyn-UG" to "UGX",
        "om-ET" to "ETB",
        "om-KE" to "KES",
        "or-IN" to "INR",
        "os-GE" to "GEL",
        "os-RU" to "RUB",
        "pa-Arab-PK" to "PKR",
        "pa-Guru-IN" to "INR",
        "pcm-NG" to "NGN",
        "pl-PL" to "PLN",
        "ps-AF" to "AFN",
        "ps-PK" to "PKR",
        "pt-AO" to "AOA",
        "pt-BR" to "BRL",
        "pt-CH" to "CHF",
        "pt-CV" to "CVE",
        "pt-GQ" to "XAF",
        "pt-GW" to "XOF",
        "pt-LU" to "EUR",
        "pt-MO" to "MOP",
        "pt-MZ" to "MZN",
        "pt-PT" to "EUR",
        "pt-ST" to "STN",
        "pt-TL" to "USD",
        "qu-BO" to "BOB",
        "qu-EC" to "USD",
        "qu-PE" to "PEN",
        "raj-IN" to "INR",
        "rm-CH" to "CHF",
        "rn-BI" to "BIF",
        "ro-MD" to "MDL",
        "ro-RO" to "RON",
        "rof-TZ" to "TZS",
        "ru-BY" to "BYN",
        "ru-KG" to "KGS",
        "ru-KZ" to "KZT",
        "ru-MD" to "MDL",
        "ru-RU" to "RUB",
        "ru-UA" to "UAH",
        "rw-RW" to "RWF",
        "rwk-TZ" to "TZS",
        "sa-IN" to "INR",
        "sah-RU" to "RUB",
        "saq-KE" to "KES",
        "sat-Olck-IN" to "INR",
        "sbp-TZ" to "TZS",
        "sc-IT" to "EUR",
        "sd-Arab-PK" to "PKR",
        "sd-Deva-IN" to "INR",
        "se-FI" to "EUR",
        "se-NO" to "NOK",
        "se-SE" to "SEK",
        "seh-MZ" to "MZN",
        "ses-ML" to "XOF",
        "sg-CF" to "XAF",
        "shi-Latn-MA" to "MAD",
        "shi-Tfng-MA" to "MAD",
        "si-LK" to "LKR",
        "sk-SK" to "EUR",
        "sl-SI" to "EUR",
        "smn-FI" to "EUR",
        "sn-ZW" to "USD",
        "so-DJ" to "DJF",
        "so-ET" to "ETB",
        "so-KE" to "KES",
        "so-SO" to "SOS",
        "sq-AL" to "ALL",
        "sq-MK" to "MKD",
        "sq-XK" to "EUR",
        "sr-Cyrl-BA" to "BAM",
        "sr-Cyrl-ME" to "EUR",
        "sr-Cyrl-RS" to "RSD",
        "sr-Cyrl-XK" to "EUR",
        "sr-Latn-BA" to "BAM",
        "sr-Latn-ME" to "EUR",
        "sr-Latn-RS" to "RSD",
        "sr-Latn-XK" to "EUR",
        "su-Latn-ID" to "IDR",
        "sv-AX" to "EUR",
        "sv-FI" to "EUR",
        "sv-SE" to "SEK",
        "sw-CD" to "CDF",
        "sw-KE" to "KES",
        "sw-TZ" to "TZS",
        "sw-UG" to "UGX",
        "ta-IN" to "INR",
        "ta-LK" to "LKR",
        "ta-MY" to "MYR",
        "ta-SG" to "SGD",
        "te-IN" to "INR",
        "teo-KE" to "KES",
        "teo-UG" to "UGX",
        "tg-TJ" to "TJS",
        "th-TH" to "THB",
        "ti-ER" to "ERN",
        "ti-ET" to "ETB",
        "tk-TM" to "TMT",
        "to-TO" to "TOP",
        "tr-CY" to "EUR",
        "tr-TR" to "TRY",
        "tt-RU" to "RUB",
        "twq-NE" to "XOF",
        "tzm-MA" to "MAD",
        "ug-CN" to "CNY",
        "uk-UA" to "UAH",
        "ur-IN" to "INR",
        "ur-PK" to "PKR",
        "uz-Arab-AF" to "AFN",
        "uz-Cyrl-UZ" to "UZS",
        "uz-Latn-UZ" to "UZS",
        "vai-Latn-LR" to "LRD",
        "vai-Vaii-LR" to "LRD",
        "vi-VN" to "VND",
        "vun-TZ" to "TZS",
        "wae-CH" to "CHF",
        "wo-SN" to "XOF",
        "xh-ZA" to "ZAR",
        "xog-UG" to "UGX",
        "yav-CM" to "XAF",
        "yi-001" to "XXX",
        "yo-BJ" to "XOF",
        "yo-NG" to "NGN",
        "yrl-BR" to "BRL",
        "yrl-CO" to "COP",
        "yrl-VE" to "VES",
        "yue-Hans-CN" to "CNY",
        "yue-Hant-HK" to "HKD",
        "zgh-MA" to "MAD",
        "zh-Hans-CN" to "CNY",
        "zh-Hans-HK" to "HKD",
        "zh-Hans-MO" to "MOP",
        "zh-Hans-SG" to "SGD",
        "zh-Hant-HK" to "HKD",
        "zh-Hant-MO" to "MOP",
        "zh-Hant-TW" to "TWD",
        "zu-ZA" to "ZAR"
    )

    val AvailableLocales = immutableMapOf(
        "af-NA" to IcuLocale("af-NA", "af", "NA", "Afrikaans (Namibia)", "$", "NAD", "afr", "NAM", null, null),
        "af-ZA" to IcuLocale("af-ZA", "af", "ZA", "Afrikaans (South Africa)", "R", "ZAR", "afr", "ZAF", null, null),
        "agq-CM" to IcuLocale("agq-CM", "agq", "CM", "Aghem (Cameroon)", "FCFA", "XAF", "agq", "CMR", null, null),
        "ak-GH" to IcuLocale("ak-GH", "ak", "GH", "Akan (Ghana)", "GH₵", "GHS", "aka", "GHA", null, null),
        "am-ET" to IcuLocale("am-ET", "am", "ET", "Amharic (Ethiopia)", "ብር", "ETB", "amh", "ETH", null, null),
        "ar-001" to IcuLocale("ar-001", "ar", "001", "Arabic (world)", "¤", "XXX", "ara", "", null, null),
        "ar-AE" to IcuLocale("ar-AE", "ar", "AE", "Arabic (United Arab Emirates)", "د.إ.‏", "AED", "ara", "ARE", null, null),
        "ar-BH" to IcuLocale("ar-BH", "ar", "BH", "Arabic (Bahrain)", "د.ب.‏", "BHD", "ara", "BHR", null, null),
        "ar-DJ" to IcuLocale("ar-DJ", "ar", "DJ", "Arabic (Djibouti)", "Fdj", "DJF", "ara", "DJI", null, null),
        "ar-DZ" to IcuLocale("ar-DZ", "ar", "DZ", "Arabic (Algeria)", "د.ج.‏", "DZD", "ara", "DZA", null, null),
        "ar-EG" to IcuLocale("ar-EG", "ar", "EG", "Arabic (Egypt)", "ج.م.‏", "EGP", "ara", "EGY", null, null),
        "ar-EH" to IcuLocale("ar-EH", "ar", "EH", "Arabic (Western Sahara)", "د.م.‏", "MAD", "ara", "ESH", null, null),
        "ar-ER" to IcuLocale("ar-ER", "ar", "ER", "Arabic (Eritrea)", "Nfk", "ERN", "ara", "ERI", null, null),
        "ar-IL" to IcuLocale("ar-IL", "ar", "IL", "Arabic (Israel)", "₪", "ILS", "ara", "ISR", null, null),
        "ar-IQ" to IcuLocale("ar-IQ", "ar", "IQ", "Arabic (Iraq)", "د.ع.‏", "IQD", "ara", "IRQ", null, null),
        "ar-JO" to IcuLocale("ar-JO", "ar", "JO", "Arabic (Jordan)", "د.أ.‏", "JOD", "ara", "JOR", null, null),
        "ar-KM" to IcuLocale("ar-KM", "ar", "KM", "Arabic (Comoros)", "CF", "KMF", "ara", "COM", null, null),
        "ar-KW" to IcuLocale("ar-KW", "ar", "KW", "Arabic (Kuwait)", "د.ك.‏", "KWD", "ara", "KWT", null, null),
        "ar-LB" to IcuLocale("ar-LB", "ar", "LB", "Arabic (Lebanon)", "ل.ل.‏", "LBP", "ara", "LBN", null, null),
        "ar-LY" to IcuLocale("ar-LY", "ar", "LY", "Arabic (Libya)", "د.ل.‏", "LYD", "ara", "LBY", null, null),
        "ar-MA" to IcuLocale("ar-MA", "ar", "MA", "Arabic (Morocco)", "د.م.‏", "MAD", "ara", "MAR", null, null),
        "ar-MR" to IcuLocale("ar-MR", "ar", "MR", "Arabic (Mauritania)", "أ.م.", "MRU", "ara", "MRT", null, null),
        "ar-OM" to IcuLocale("ar-OM", "ar", "OM", "Arabic (Oman)", "ر.ع.‏", "OMR", "ara", "OMN", null, null),
        "ar-PS" to IcuLocale("ar-PS", "ar", "PS", "Arabic (Palestinian Territories)", "₪", "ILS", "ara", "PSE", null, null),
        "ar-QA" to IcuLocale("ar-QA", "ar", "QA", "Arabic (Qatar)", "ر.ق.‏", "QAR", "ara", "QAT", null, null),
        "ar-SA" to IcuLocale("ar-SA", "ar", "SA", "Arabic (Saudi Arabia)", "ر.س.‏", "SAR", "ara", "SAU", null, null),
        "ar-SD" to IcuLocale("ar-SD", "ar", "SD", "Arabic (Sudan)", "ج.س.", "SDG", "ara", "SDN", null, null),
        "ar-SO" to IcuLocale("ar-SO", "ar", "SO", "Arabic (Somalia)", "S", "SOS", "ara", "SOM", null, null),
        "ar-SS" to IcuLocale("ar-SS", "ar", "SS", "Arabic (South Sudan)", "£", "SSP", "ara", "SSD", null, null),
        "ar-SY" to IcuLocale("ar-SY", "ar", "SY", "Arabic (Syria)", "ل.س.‏", "SYP", "ara", "SYR", null, null),
        "ar-TD" to IcuLocale("ar-TD", "ar", "TD", "Arabic (Chad)", "FCFA", "XAF", "ara", "TCD", null, null),
        "ar-TN" to IcuLocale("ar-TN", "ar", "TN", "Arabic (Tunisia)", "د.ت.‏", "TND", "ara", "TUN", null, null),
        "ar-YE" to IcuLocale("ar-YE", "ar", "YE", "Arabic (Yemen)", "ر.ي.‏", "YER", "ara", "YEM", null, null),
        "as-IN" to IcuLocale("as-IN", "as", "IN", "Assamese (India)", "₹", "INR", "asm", "IND", null, null),
        "asa-TZ" to IcuLocale("asa-TZ", "asa", "TZ", "Asu (Tanzania)", "TSh", "TZS", "asa", "TZA", null, null),
        "ast-ES" to IcuLocale("ast-ES", "ast", "ES", "Asturian (Spain)", "€", "EUR", "ast", "ESP", null, null),
        "az-Cyrl-AZ" to IcuLocale("az-Cyrl-AZ", "az", "AZ", "Azerbaijani (Cyrillic, Azerbaijan)", "₼", "AZN", "aze", "AZE", "Cyrillic", null),
        "az-Latn-AZ" to IcuLocale("az-Latn-AZ", "az", "AZ", "Azerbaijani (Latin, Azerbaijan)", "₼", "AZN", "aze", "AZE", "Latin", null),
        "bas-CM" to IcuLocale("bas-CM", "bas", "CM", "Basaa (Cameroon)", "FCFA", "XAF", "bas", "CMR", null, null),
        "be-BY" to IcuLocale("be-BY", "be", "BY", "Belarusian (Belarus)", "Br", "BYN", "bel", "BLR", null, null),
        "bem-ZM" to IcuLocale("bem-ZM", "bem", "ZM", "Bemba (Zambia)", "K", "ZMW", "bem", "ZMB", null, null),
        "bez-TZ" to IcuLocale("bez-TZ", "bez", "TZ", "Bena (Tanzania)", "TSh", "TZS", "bez", "TZA", null, null),
        "bg-BG" to IcuLocale("bg-BG", "bg", "BG", "Bulgarian (Bulgaria)", "лв.", "BGN", "bul", "BGR", null, null),
        "bgc-IN" to IcuLocale("bgc-IN", "bgc", "IN", "Haryanvi (India)", "₹", "INR", "bgc", "IND", null, null),
        "bho-IN" to IcuLocale("bho-IN", "bho", "IN", "Bhojpuri (India)", "₹", "INR", "bho", "IND", null, null),
        "bm-ML" to IcuLocale("bm-ML", "bm", "ML", "Bambara (Mali)", "F CFA", "XOF", "bam", "MLI", null, null),
        "bn-BD" to IcuLocale("bn-BD", "bn", "BD", "Bangla (Bangladesh)", "৳", "BDT", "ben", "BGD", null, null),
        "bn-IN" to IcuLocale("bn-IN", "bn", "IN", "Bangla (India)", "₹", "INR", "ben", "IND", null, null),
        "bo-CN" to IcuLocale("bo-CN", "bo", "CN", "Tibetan (China)", "¥", "CNY", "bod", "CHN", null, null),
        "bo-IN" to IcuLocale("bo-IN", "bo", "IN", "Tibetan (India)", "₹", "INR", "bod", "IND", null, null),
        "br-FR" to IcuLocale("br-FR", "br", "FR", "Breton (France)", "€", "EUR", "bre", "FRA", null, null),
        "brx-IN" to IcuLocale("brx-IN", "brx", "IN", "Bodo (India)", "₹", "INR", "brx", "IND", null, null),
        "bs-Cyrl-BA" to IcuLocale("bs-Cyrl-BA", "bs", "BA", "Bosnian (Cyrillic, Bosnia & Herzegovina)", "КМ", "BAM", "bos", "BIH", "Cyrillic", null),
        "bs-Latn-BA" to IcuLocale("bs-Latn-BA", "bs", "BA", "Bosnian (Latin, Bosnia & Herzegovina)", "KM", "BAM", "bos", "BIH", "Latin", null),
        "ca-AD" to IcuLocale("ca-AD", "ca", "AD", "Catalan (Andorra)", "€", "EUR", "cat", "AND", null, null),
        "ca-ES" to IcuLocale("ca-ES", "ca", "ES", "Catalan (Spain)", "€", "EUR", "cat", "ESP", null, null),
        "ca-FR" to IcuLocale("ca-FR", "ca", "FR", "Catalan (France)", "€", "EUR", "cat", "FRA", null, null),
        "ca-IT" to IcuLocale("ca-IT", "ca", "IT", "Catalan (Italy)", "€", "EUR", "cat", "ITA", null, null),
        "ccp-BD" to IcuLocale("ccp-BD", "ccp", "BD", "Chakma (Bangladesh)", "৳", "BDT", "ccp", "BGD", null, null),
        "ccp-IN" to IcuLocale("ccp-IN", "ccp", "IN", "Chakma (India)", "₹", "INR", "ccp", "IND", null, null),
        "ce-RU" to IcuLocale("ce-RU", "ce", "RU", "Chechen (Russia)", "₽", "RUB", "che", "RUS", null, null),
        "ceb-PH" to IcuLocale("ceb-PH", "ceb", "PH", "Cebuano (Philippines)", "₱", "PHP", "ceb", "PHL", null, null),
        "cgg-UG" to IcuLocale("cgg-UG", "cgg", "UG", "Chiga (Uganda)", "USh", "UGX", "cgg", "UGA", null, null),
        "chr-US" to IcuLocale("chr-US", "chr", "US", "Cherokee (United States)", "$", "USD", "chr", "USA", null, null),
        "ckb-IQ" to IcuLocale("ckb-IQ", "ckb", "IQ", "Central Kurdish (Iraq)", "د.ع.‏", "IQD", "ckb", "IRQ", null, null),
        "ckb-IR" to IcuLocale("ckb-IR", "ckb", "IR", "Central Kurdish (Iran)", "IRR", "IRR", "ckb", "IRN", null, null),
        "cs-CZ" to IcuLocale("cs-CZ", "cs", "CZ", "Czech (Czechia)", "Kč", "CZK", "ces", "CZE", null, null),
        "cv-RU" to IcuLocale("cv-RU", "cv", "RU", "Chuvash (Russia)", "₽", "RUB", "chv", "RUS", null, null),
        "cy-GB" to IcuLocale("cy-GB", "cy", "GB", "Welsh (United Kingdom)", "£", "GBP", "cym", "GBR", null, null),
        "da-DK" to IcuLocale("da-DK", "da", "DK", "Danish (Denmark)", "kr.", "DKK", "dan", "DNK", null, null),
        "da-GL" to IcuLocale("da-GL", "da", "GL", "Danish (Greenland)", "kr.", "DKK", "dan", "GRL", null, null),
        "dav-KE" to IcuLocale("dav-KE", "dav", "KE", "Taita (Kenya)", "Ksh", "KES", "dav", "KEN", null, null),
        "de-AT" to IcuLocale("de-AT", "de", "AT", "German (Austria)", "€", "EUR", "deu", "AUT", null, null),
        "de-BE" to IcuLocale("de-BE", "de", "BE", "German (Belgium)", "€", "EUR", "deu", "BEL", null, null),
        "de-CH" to IcuLocale("de-CH", "de", "CH", "German (Switzerland)", "CHF", "CHF", "deu", "CHE", null, null),
        "de-DE" to IcuLocale("de-DE", "de", "DE", "German (Germany)", "€", "EUR", "deu", "DEU", null, null),
        "de-IT" to IcuLocale("de-IT", "de", "IT", "German (Italy)", "€", "EUR", "deu", "ITA", null, null),
        "de-LI" to IcuLocale("de-LI", "de", "LI", "German (Liechtenstein)", "CHF", "CHF", "deu", "LIE", null, null),
        "de-LU" to IcuLocale("de-LU", "de", "LU", "German (Luxembourg)", "€", "EUR", "deu", "LUX", null, null),
        "dje-NE" to IcuLocale("dje-NE", "dje", "NE", "Zarma (Niger)", "F CFA", "XOF", "dje", "NER", null, null),
        "doi-IN" to IcuLocale("doi-IN", "doi", "IN", "Dogri (India)", "₹", "INR", "doi", "IND", null, null),
        "dsb-DE" to IcuLocale("dsb-DE", "dsb", "DE", "Lower Sorbian (Germany)", "€", "EUR", "dsb", "DEU", null, null),
        "dua-CM" to IcuLocale("dua-CM", "dua", "CM", "Duala (Cameroon)", "FCFA", "XAF", "dua", "CMR", null, null),
        "dyo-SN" to IcuLocale("dyo-SN", "dyo", "SN", "Jola-Fonyi (Senegal)", "F CFA", "XOF", "dyo", "SEN", null, null),
        "dz-BT" to IcuLocale("dz-BT", "dz", "BT", "Dzongkha (Bhutan)", "Nu.", "BTN", "dzo", "BTN", null, null),
        "ebu-KE" to IcuLocale("ebu-KE", "ebu", "KE", "Embu (Kenya)", "Ksh", "KES", "ebu", "KEN", null, null),
        "ee-GH" to IcuLocale("ee-GH", "ee", "GH", "Ewe (Ghana)", "GH₵", "GHS", "ewe", "GHA", null, null),
        "ee-TG" to IcuLocale("ee-TG", "ee", "TG", "Ewe (Togo)", "F CFA", "XOF", "ewe", "TGO", null, null),
        "el-CY" to IcuLocale("el-CY", "el", "CY", "Greek (Cyprus)", "€", "EUR", "ell", "CYP", null, null),
        "el-GR" to IcuLocale("el-GR", "el", "GR", "Greek (Greece)", "€", "EUR", "ell", "GRC", null, null),
        "en-001" to IcuLocale("en-001", "en", "001", "English (world)", "¤", "XXX", "eng", "", null, null),
        "en-150" to IcuLocale("en-150", "en", "150", "English (Europe)", "¤", "XXX", "eng", "", null, null),
        "en-AE" to IcuLocale("en-AE", "en", "AE", "English (United Arab Emirates)", "AED", "AED", "eng", "ARE", null, null),
        "en-AG" to IcuLocale("en-AG", "en", "AG", "English (Antigua & Barbuda)", "$", "XCD", "eng", "ATG", null, null),
        "en-AI" to IcuLocale("en-AI", "en", "AI", "English (Anguilla)", "$", "XCD", "eng", "AIA", null, null),
        "en-AS" to IcuLocale("en-AS", "en", "AS", "English (American Samoa)", "$", "USD", "eng", "ASM", null, null),
        "en-AT" to IcuLocale("en-AT", "en", "AT", "English (Austria)", "€", "EUR", "eng", "AUT", null, null),
        "en-AU" to IcuLocale("en-AU", "en", "AU", "English (Australia)", "$", "AUD", "eng", "AUS", null, null),
        "en-BB" to IcuLocale("en-BB", "en", "BB", "English (Barbados)", "$", "BBD", "eng", "BRB", null, null),
        "en-BE" to IcuLocale("en-BE", "en", "BE", "English (Belgium)", "€", "EUR", "eng", "BEL", null, null),
        "en-BI" to IcuLocale("en-BI", "en", "BI", "English (Burundi)", "FBu", "BIF", "eng", "BDI", null, null),
        "en-BM" to IcuLocale("en-BM", "en", "BM", "English (Bermuda)", "$", "BMD", "eng", "BMU", null, null),
        "en-BS" to IcuLocale("en-BS", "en", "BS", "English (Bahamas)", "$", "BSD", "eng", "BHS", null, null),
        "en-BW" to IcuLocale("en-BW", "en", "BW", "English (Botswana)", "P", "BWP", "eng", "BWA", null, null),
        "en-BZ" to IcuLocale("en-BZ", "en", "BZ", "English (Belize)", "$", "BZD", "eng", "BLZ", null, null),
        "en-CA" to IcuLocale("en-CA", "en", "CA", "English (Canada)", "$", "CAD", "eng", "CAN", null, null),
        "en-CC" to IcuLocale("en-CC", "en", "CC", "English (Cocos [Keeling] Islands)", "$", "AUD", "eng", "CCK", null, null),
        "en-CH" to IcuLocale("en-CH", "en", "CH", "English (Switzerland)", "CHF", "CHF", "eng", "CHE", null, null),
        "en-CK" to IcuLocale("en-CK", "en", "CK", "English (Cook Islands)", "$", "NZD", "eng", "COK", null, null),
        "en-CM" to IcuLocale("en-CM", "en", "CM", "English (Cameroon)", "FCFA", "XAF", "eng", "CMR", null, null),
        "en-CX" to IcuLocale("en-CX", "en", "CX", "English (Christmas Island)", "$", "AUD", "eng", "CXR", null, null),
        "en-CY" to IcuLocale("en-CY", "en", "CY", "English (Cyprus)", "€", "EUR", "eng", "CYP", null, null),
        "en-DE" to IcuLocale("en-DE", "en", "DE", "English (Germany)", "€", "EUR", "eng", "DEU", null, null),
        "en-DG" to IcuLocale("en-DG", "en", "DG", "English (Diego Garcia)", "US$", "USD", "eng", "DGA", null, null),
        "en-DK" to IcuLocale("en-DK", "en", "DK", "English (Denmark)", "kr.", "DKK", "eng", "DNK", null, null),
        "en-DM" to IcuLocale("en-DM", "en", "DM", "English (Dominica)", "$", "XCD", "eng", "DMA", null, null),
        "en-ER" to IcuLocale("en-ER", "en", "ER", "English (Eritrea)", "Nfk", "ERN", "eng", "ERI", null, null),
        "en-FI" to IcuLocale("en-FI", "en", "FI", "English (Finland)", "€", "EUR", "eng", "FIN", null, null),
        "en-FJ" to IcuLocale("en-FJ", "en", "FJ", "English (Fiji)", "$", "FJD", "eng", "FJI", null, null),
        "en-FK" to IcuLocale("en-FK", "en", "FK", "English (Falkland Islands)", "£", "FKP", "eng", "FLK", null, null),
        "en-FM" to IcuLocale("en-FM", "en", "FM", "English (Micronesia)", "US$", "USD", "eng", "FSM", null, null),
        "en-GB" to IcuLocale("en-GB", "en", "GB", "English (United Kingdom)", "£", "GBP", "eng", "GBR", null, null),
        "en-GD" to IcuLocale("en-GD", "en", "GD", "English (Grenada)", "$", "XCD", "eng", "GRD", null, null),
        "en-GG" to IcuLocale("en-GG", "en", "GG", "English (Guernsey)", "£", "GBP", "eng", "GGY", null, null),
        "en-GH" to IcuLocale("en-GH", "en", "GH", "English (Ghana)", "GH₵", "GHS", "eng", "GHA", null, null),
        "en-GI" to IcuLocale("en-GI", "en", "GI", "English (Gibraltar)", "£", "GIP", "eng", "GIB", null, null),
        "en-GM" to IcuLocale("en-GM", "en", "GM", "English (Gambia)", "D", "GMD", "eng", "GMB", null, null),
        "en-GU" to IcuLocale("en-GU", "en", "GU", "English (Guam)", "$", "USD", "eng", "GUM", null, null),
        "en-GY" to IcuLocale("en-GY", "en", "GY", "English (Guyana)", "$", "GYD", "eng", "GUY", null, null),
        "en-HK" to IcuLocale("en-HK", "en", "HK", "English (Hong Kong SAR China)", "HK$", "HKD", "eng", "HKG", null, null),
        "en-IE" to IcuLocale("en-IE", "en", "IE", "English (Ireland)", "€", "EUR", "eng", "IRL", null, null),
        "en-IL" to IcuLocale("en-IL", "en", "IL", "English (Israel)", "₪", "ILS", "eng", "ISR", null, null),
        "en-IM" to IcuLocale("en-IM", "en", "IM", "English (Isle of Man)", "£", "GBP", "eng", "IMN", null, null),
        "en-IN" to IcuLocale("en-IN", "en", "IN", "English (India)", "₹", "INR", "eng", "IND", null, null),
        "en-IO" to IcuLocale("en-IO", "en", "IO", "English (British Indian Ocean Territory)", "US$", "USD", "eng", "IOT", null, null),
        "en-JE" to IcuLocale("en-JE", "en", "JE", "English (Jersey)", "£", "GBP", "eng", "JEY", null, null),
        "en-JM" to IcuLocale("en-JM", "en", "JM", "English (Jamaica)", "$", "JMD", "eng", "JAM", null, null),
        "en-KE" to IcuLocale("en-KE", "en", "KE", "English (Kenya)", "Ksh", "KES", "eng", "KEN", null, null),
        "en-KI" to IcuLocale("en-KI", "en", "KI", "English (Kiribati)", "$", "AUD", "eng", "KIR", null, null),
        "en-KN" to IcuLocale("en-KN", "en", "KN", "English (St. Kitts & Nevis)", "$", "XCD", "eng", "KNA", null, null),
        "en-KY" to IcuLocale("en-KY", "en", "KY", "English (Cayman Islands)", "$", "KYD", "eng", "CYM", null, null),
        "en-LC" to IcuLocale("en-LC", "en", "LC", "English (St. Lucia)", "$", "XCD", "eng", "LCA", null, null),
        "en-LR" to IcuLocale("en-LR", "en", "LR", "English (Liberia)", "$", "LRD", "eng", "LBR", null, null),
        "en-LS" to IcuLocale("en-LS", "en", "LS", "English (Lesotho)", "R", "ZAR", "eng", "LSO", null, null),
        "en-MG" to IcuLocale("en-MG", "en", "MG", "English (Madagascar)", "Ar", "MGA", "eng", "MDG", null, null),
        "en-MH" to IcuLocale("en-MH", "en", "MH", "English (Marshall Islands)", "$", "USD", "eng", "MHL", null, null),
        "en-MO" to IcuLocale("en-MO", "en", "MO", "English (Macao SAR China)", "MOP$", "MOP", "eng", "MAC", null, null),
        "en-MP" to IcuLocale("en-MP", "en", "MP", "English (Northern Mariana Islands)", "$", "USD", "eng", "MNP", null, null),
        "en-MS" to IcuLocale("en-MS", "en", "MS", "English (Montserrat)", "$", "XCD", "eng", "MSR", null, null),
        "en-MT" to IcuLocale("en-MT", "en", "MT", "English (Malta)", "€", "EUR", "eng", "MLT", null, null),
        "en-MU" to IcuLocale("en-MU", "en", "MU", "English (Mauritius)", "Rs", "MUR", "eng", "MUS", null, null),
        "en-MV" to IcuLocale("en-MV", "en", "MV", "English (Maldives)", "Rf", "MVR", "eng", "MDV", null, null),
        "en-MW" to IcuLocale("en-MW", "en", "MW", "English (Malawi)", "MK", "MWK", "eng", "MWI", null, null),
        "en-MY" to IcuLocale("en-MY", "en", "MY", "English (Malaysia)", "RM", "MYR", "eng", "MYS", null, null),
        "en-NA" to IcuLocale("en-NA", "en", "NA", "English (Namibia)", "$", "NAD", "eng", "NAM", null, null),
        "en-NF" to IcuLocale("en-NF", "en", "NF", "English (Norfolk Island)", "$", "AUD", "eng", "NFK", null, null),
        "en-NG" to IcuLocale("en-NG", "en", "NG", "English (Nigeria)", "₦", "NGN", "eng", "NGA", null, null),
        "en-NL" to IcuLocale("en-NL", "en", "NL", "English (Netherlands)", "€", "EUR", "eng", "NLD", null, null),
        "en-NR" to IcuLocale("en-NR", "en", "NR", "English (Nauru)", "$", "AUD", "eng", "NRU", null, null),
        "en-NU" to IcuLocale("en-NU", "en", "NU", "English (Niue)", "$", "NZD", "eng", "NIU", null, null),
        "en-NZ" to IcuLocale("en-NZ", "en", "NZ", "English (New Zealand)", "$", "NZD", "eng", "NZL", null, null),
        "en-PG" to IcuLocale("en-PG", "en", "PG", "English (Papua New Guinea)", "K", "PGK", "eng", "PNG", null, null),
        "en-PH" to IcuLocale("en-PH", "en", "PH", "English (Philippines)", "₱", "PHP", "eng", "PHL", null, null),
        "en-PK" to IcuLocale("en-PK", "en", "PK", "English (Pakistan)", "Rs", "PKR", "eng", "PAK", null, null),
        "en-PN" to IcuLocale("en-PN", "en", "PN", "English (Pitcairn Islands)", "$", "NZD", "eng", "PCN", null, null),
        "en-PR" to IcuLocale("en-PR", "en", "PR", "English (Puerto Rico)", "$", "USD", "eng", "PRI", null, null),
        "en-PW" to IcuLocale("en-PW", "en", "PW", "English (Palau)", "US$", "USD", "eng", "PLW", null, null),
        "en-RW" to IcuLocale("en-RW", "en", "RW", "English (Rwanda)", "RF", "RWF", "eng", "RWA", null, null),
        "en-SB" to IcuLocale("en-SB", "en", "SB", "English (Solomon Islands)", "$", "SBD", "eng", "SLB", null, null),
        "en-SC" to IcuLocale("en-SC", "en", "SC", "English (Seychelles)", "SR", "SCR", "eng", "SYC", null, null),
        "en-SD" to IcuLocale("en-SD", "en", "SD", "English (Sudan)", "SDG", "SDG", "eng", "SDN", null, null),
        "en-SE" to IcuLocale("en-SE", "en", "SE", "English (Sweden)", "kr", "SEK", "eng", "SWE", null, null),
        "en-SG" to IcuLocale("en-SG", "en", "SG", "English (Singapore)", "$", "SGD", "eng", "SGP", null, null),
        "en-SH" to IcuLocale("en-SH", "en", "SH", "English (St. Helena)", "£", "SHP", "eng", "SHN", null, null),
        "en-SI" to IcuLocale("en-SI", "en", "SI", "English (Slovenia)", "€", "EUR", "eng", "SVN", null, null),
        "en-SL" to IcuLocale("en-SL", "en", "SL", "English (Sierra Leone)", "Le", "SLE", "eng", "SLE", null, null),
        "en-SS" to IcuLocale("en-SS", "en", "SS", "English (South Sudan)", "£", "SSP", "eng", "SSD", null, null),
        "en-SX" to IcuLocale("en-SX", "en", "SX", "English (Sint Maarten)", "NAf.", "ANG", "eng", "SXM", null, null),
        "en-SZ" to IcuLocale("en-SZ", "en", "SZ", "English (Eswatini)", "E", "SZL", "eng", "SWZ", null, null),
        "en-TC" to IcuLocale("en-TC", "en", "TC", "English (Turks & Caicos Islands)", "US$", "USD", "eng", "TCA", null, null),
        "en-TK" to IcuLocale("en-TK", "en", "TK", "English (Tokelau)", "$", "NZD", "eng", "TKL", null, null),
        "en-TO" to IcuLocale("en-TO", "en", "TO", "English (Tonga)", "T$", "TOP", "eng", "TON", null, null),
        "en-TT" to IcuLocale("en-TT", "en", "TT", "English (Trinidad & Tobago)", "$", "TTD", "eng", "TTO", null, null),
        "en-TV" to IcuLocale("en-TV", "en", "TV", "English (Tuvalu)", "$", "AUD", "eng", "TUV", null, null),
        "en-TZ" to IcuLocale("en-TZ", "en", "TZ", "English (Tanzania)", "TSh", "TZS", "eng", "TZA", null, null),
        "en-UG" to IcuLocale("en-UG", "en", "UG", "English (Uganda)", "USh", "UGX", "eng", "UGA", null, null),
        "en-UM" to IcuLocale("en-UM", "en", "UM", "English (U.S. Outlying Islands)", "$", "USD", "eng", "UMI", null, null),
        "en-US" to IcuLocale("en-US", "en", "US", "English (United States)", "$", "USD", "eng", "USA", null, null),
        "en-US-u-va-posix" to IcuLocale("en-US-u-va-posix", "en", "US", "English (United States, Computer)", "$", "USD", "eng", "USA", null, "Computer"),
        "en-VC" to IcuLocale("en-VC", "en", "VC", "English (St. Vincent & Grenadines)", "$", "XCD", "eng", "VCT", null, null),
        "en-VG" to IcuLocale("en-VG", "en", "VG", "English (British Virgin Islands)", "US$", "USD", "eng", "VGB", null, null),
        "en-VI" to IcuLocale("en-VI", "en", "VI", "English (U.S. Virgin Islands)", "$", "USD", "eng", "VIR", null, null),
        "en-VU" to IcuLocale("en-VU", "en", "VU", "English (Vanuatu)", "VT", "VUV", "eng", "VUT", null, null),
        "en-WS" to IcuLocale("en-WS", "en", "WS", "English (Samoa)", "WS$", "WST", "eng", "WSM", null, null),
        "en-ZA" to IcuLocale("en-ZA", "en", "ZA", "English (South Africa)", "R", "ZAR", "eng", "ZAF", null, null),
        "en-ZM" to IcuLocale("en-ZM", "en", "ZM", "English (Zambia)", "K", "ZMW", "eng", "ZMB", null, null),
        "en-ZW" to IcuLocale("en-ZW", "en", "ZW", "English (Zimbabwe)", "US$", "USD", "eng", "ZWE", null, null),
        "eo-001" to IcuLocale("eo-001", "eo", "001", "Esperanto (world)", "¤", "XXX", "epo", "", null, null),
        "es-419" to IcuLocale("es-419", "es", "419", "Spanish (Latin America)", "¤", "XXX", "spa", "", null, null),
        "es-AR" to IcuLocale("es-AR", "es", "AR", "Spanish (Argentina)", "$", "ARS", "spa", "ARG", null, null),
        "es-BO" to IcuLocale("es-BO", "es", "BO", "Spanish (Bolivia)", "Bs", "BOB", "spa", "BOL", null, null),
        "es-BR" to IcuLocale("es-BR", "es", "BR", "Spanish (Brazil)", "R$", "BRL", "spa", "BRA", null, null),
        "es-BZ" to IcuLocale("es-BZ", "es", "BZ", "Spanish (Belize)", "$", "BZD", "spa", "BLZ", null, null),
        "es-CL" to IcuLocale("es-CL", "es", "CL", "Spanish (Chile)", "$", "CLP", "spa", "CHL", null, null),
        "es-CO" to IcuLocale("es-CO", "es", "CO", "Spanish (Colombia)", "$", "COP", "spa", "COL", null, null),
        "es-CR" to IcuLocale("es-CR", "es", "CR", "Spanish (Costa Rica)", "₡", "CRC", "spa", "CRI", null, null),
        "es-CU" to IcuLocale("es-CU", "es", "CU", "Spanish (Cuba)", "$", "CUP", "spa", "CUB", null, null),
        "es-DO" to IcuLocale("es-DO", "es", "DO", "Spanish (Dominican Republic)", "RD$", "DOP", "spa", "DOM", null, null),
        "es-EA" to IcuLocale("es-EA", "es", "EA", "Spanish (Ceuta & Melilla)", "€", "EUR", "spa", "XEA", null, null),
        "es-EC" to IcuLocale("es-EC", "es", "EC", "Spanish (Ecuador)", "$", "USD", "spa", "ECU", null, null),
        "es-ES" to IcuLocale("es-ES", "es", "ES", "Spanish (Spain)", "€", "EUR", "spa", "ESP", null, null),
        "es-GQ" to IcuLocale("es-GQ", "es", "GQ", "Spanish (Equatorial Guinea)", "FCFA", "XAF", "spa", "GNQ", null, null),
        "es-GT" to IcuLocale("es-GT", "es", "GT", "Spanish (Guatemala)", "Q", "GTQ", "spa", "GTM", null, null),
        "es-HN" to IcuLocale("es-HN", "es", "HN", "Spanish (Honduras)", "L", "HNL", "spa", "HND", null, null),
        "es-IC" to IcuLocale("es-IC", "es", "IC", "Spanish (Canary Islands)", "€", "EUR", "spa", "XIC", null, null),
        "es-MX" to IcuLocale("es-MX", "es", "MX", "Spanish (Mexico)", "$", "MXN", "spa", "MEX", null, null),
        "es-NI" to IcuLocale("es-NI", "es", "NI", "Spanish (Nicaragua)", "C$", "NIO", "spa", "NIC", null, null),
        "es-PA" to IcuLocale("es-PA", "es", "PA", "Spanish (Panama)", "B/.", "PAB", "spa", "PAN", null, null),
        "es-PE" to IcuLocale("es-PE", "es", "PE", "Spanish (Peru)", "S/", "PEN", "spa", "PER", null, null),
        "es-PH" to IcuLocale("es-PH", "es", "PH", "Spanish (Philippines)", "₱", "PHP", "spa", "PHL", null, null),
        "es-PR" to IcuLocale("es-PR", "es", "PR", "Spanish (Puerto Rico)", "$", "USD", "spa", "PRI", null, null),
        "es-PY" to IcuLocale("es-PY", "es", "PY", "Spanish (Paraguay)", "Gs.", "PYG", "spa", "PRY", null, null),
        "es-SV" to IcuLocale("es-SV", "es", "SV", "Spanish (El Salvador)", "$", "USD", "spa", "SLV", null, null),
        "es-US" to IcuLocale("es-US", "es", "US", "Spanish (United States)", "$", "USD", "spa", "USA", null, null),
        "es-UY" to IcuLocale("es-UY", "es", "UY", "Spanish (Uruguay)", "$", "UYU", "spa", "URY", null, null),
        "es-VE" to IcuLocale("es-VE", "es", "VE", "Spanish (Venezuela)", "Bs.S", "VES", "spa", "VEN", null, null),
        "et-EE" to IcuLocale("et-EE", "et", "EE", "Estonian (Estonia)", "€", "EUR", "est", "EST", null, null),
        "eu-ES" to IcuLocale("eu-ES", "eu", "ES", "Basque (Spain)", "€", "EUR", "eus", "ESP", null, null),
        "ewo-CM" to IcuLocale("ewo-CM", "ewo", "CM", "Ewondo (Cameroon)", "FCFA", "XAF", "ewo", "CMR", null, null),
        "fa-AF" to IcuLocale("fa-AF", "fa", "AF", "Persian (Afghanistan)", "؋", "AFN", "fas", "AFG", null, null),
        "fa-IR" to IcuLocale("fa-IR", "fa", "IR", "Persian (Iran)", "ریال", "IRR", "fas", "IRN", null, null),
        "ff-Adlm-BF" to IcuLocale("ff-Adlm-BF", "ff", "BF", "Fula (Adlam, Burkina Faso)", "𞤅𞤊𞤀", "XOF", "ful", "BFA", "Adlam", null),
        "ff-Adlm-CM" to IcuLocale("ff-Adlm-CM", "ff", "CM", "Fula (Adlam, Cameroon)", "𞤊𞤅𞤊𞤀", "XAF", "ful", "CMR", "Adlam", null),
        "ff-Adlm-GH" to IcuLocale("ff-Adlm-GH", "ff", "GH", "Fula (Adlam, Ghana)", "GH₵", "GHS", "ful", "GHA", "Adlam", null),
        "ff-Adlm-GM" to IcuLocale("ff-Adlm-GM", "ff", "GM", "Fula (Adlam, Gambia)", "D", "GMD", "ful", "GMB", "Adlam", null),
        "ff-Adlm-GN" to IcuLocale("ff-Adlm-GN", "ff", "GN", "Fula (Adlam, Guinea)", "FG", "GNF", "ful", "GIN", "Adlam", null),
        "ff-Adlm-GW" to IcuLocale("ff-Adlm-GW", "ff", "GW", "Fula (Adlam, Guinea-Bissau)", "𞤅𞤊𞤀", "XOF", "ful", "GNB", "Adlam", null),
        "ff-Adlm-LR" to IcuLocale("ff-Adlm-LR", "ff", "LR", "Fula (Adlam, Liberia)", "$", "LRD", "ful", "LBR", "Adlam", null),
        "ff-Adlm-MR" to IcuLocale("ff-Adlm-MR", "ff", "MR", "Fula (Adlam, Mauritania)", "UM", "MRU", "ful", "MRT", "Adlam", null),
        "ff-Adlm-NE" to IcuLocale("ff-Adlm-NE", "ff", "NE", "Fula (Adlam, Niger)", "𞤅𞤊𞤀", "XOF", "ful", "NER", "Adlam", null),
        "ff-Adlm-NG" to IcuLocale("ff-Adlm-NG", "ff", "NG", "Fula (Adlam, Nigeria)", "₦", "NGN", "ful", "NGA", "Adlam", null),
        "ff-Adlm-SL" to IcuLocale("ff-Adlm-SL", "ff", "SL", "Fula (Adlam, Sierra Leone)", "Le", "SLE", "ful", "SLE", "Adlam", null),
        "ff-Adlm-SN" to IcuLocale("ff-Adlm-SN", "ff", "SN", "Fula (Adlam, Senegal)", "𞤅𞤊𞤀", "XOF", "ful", "SEN", "Adlam", null),
        "ff-Latn-BF" to IcuLocale("ff-Latn-BF", "ff", "BF", "Fula (Latin, Burkina Faso)", "F CFA", "XOF", "ful", "BFA", "Latin", null),
        "ff-Latn-CM" to IcuLocale("ff-Latn-CM", "ff", "CM", "Fula (Latin, Cameroon)", "FCFA", "XAF", "ful", "CMR", "Latin", null),
        "ff-Latn-GH" to IcuLocale("ff-Latn-GH", "ff", "GH", "Fula (Latin, Ghana)", "GH₵", "GHS", "ful", "GHA", "Latin", null),
        "ff-Latn-GM" to IcuLocale("ff-Latn-GM", "ff", "GM", "Fula (Latin, Gambia)", "D", "GMD", "ful", "GMB", "Latin", null),
        "ff-Latn-GN" to IcuLocale("ff-Latn-GN", "ff", "GN", "Fula (Latin, Guinea)", "FG", "GNF", "ful", "GIN", "Latin", null),
        "ff-Latn-GW" to IcuLocale("ff-Latn-GW", "ff", "GW", "Fula (Latin, Guinea-Bissau)", "F CFA", "XOF", "ful", "GNB", "Latin", null),
        "ff-Latn-LR" to IcuLocale("ff-Latn-LR", "ff", "LR", "Fula (Latin, Liberia)", "$", "LRD", "ful", "LBR", "Latin", null),
        "ff-Latn-MR" to IcuLocale("ff-Latn-MR", "ff", "MR", "Fula (Latin, Mauritania)", "UM", "MRU", "ful", "MRT", "Latin", null),
        "ff-Latn-NE" to IcuLocale("ff-Latn-NE", "ff", "NE", "Fula (Latin, Niger)", "F CFA", "XOF", "ful", "NER", "Latin", null),
        "ff-Latn-NG" to IcuLocale("ff-Latn-NG", "ff", "NG", "Fula (Latin, Nigeria)", "₦", "NGN", "ful", "NGA", "Latin", null),
        "ff-Latn-SL" to IcuLocale("ff-Latn-SL", "ff", "SL", "Fula (Latin, Sierra Leone)", "Le", "SLE", "ful", "SLE", "Latin", null),
        "ff-Latn-SN" to IcuLocale("ff-Latn-SN", "ff", "SN", "Fula (Latin, Senegal)", "F CFA", "XOF", "ful", "SEN", "Latin", null),
        "fi-FI" to IcuLocale("fi-FI", "fi", "FI", "Finnish (Finland)", "€", "EUR", "fin", "FIN", null, null),
        "fil-PH" to IcuLocale("fil-PH", "fil", "PH", "Filipino (Philippines)", "₱", "PHP", "fil", "PHL", null, null),
        "fo-DK" to IcuLocale("fo-DK", "fo", "DK", "Faroese (Denmark)", "kr.", "DKK", "fao", "DNK", null, null),
        "fo-FO" to IcuLocale("fo-FO", "fo", "FO", "Faroese (Faroe Islands)", "kr", "DKK", "fao", "FRO", null, null),
        "fr-BE" to IcuLocale("fr-BE", "fr", "BE", "French (Belgium)", "€", "EUR", "fra", "BEL", null, null),
        "fr-BF" to IcuLocale("fr-BF", "fr", "BF", "French (Burkina Faso)", "F CFA", "XOF", "fra", "BFA", null, null),
        "fr-BI" to IcuLocale("fr-BI", "fr", "BI", "French (Burundi)", "FBu", "BIF", "fra", "BDI", null, null),
        "fr-BJ" to IcuLocale("fr-BJ", "fr", "BJ", "French (Benin)", "F CFA", "XOF", "fra", "BEN", null, null),
        "fr-BL" to IcuLocale("fr-BL", "fr", "BL", "French (St. Barthélemy)", "€", "EUR", "fra", "BLM", null, null),
        "fr-CA" to IcuLocale("fr-CA", "fr", "CA", "French (Canada)", "$", "CAD", "fra", "CAN", null, null),
        "fr-CD" to IcuLocale("fr-CD", "fr", "CD", "French (Congo - Kinshasa)", "FC", "CDF", "fra", "COD", null, null),
        "fr-CF" to IcuLocale("fr-CF", "fr", "CF", "French (Central African Republic)", "FCFA", "XAF", "fra", "CAF", null, null),
        "fr-CG" to IcuLocale("fr-CG", "fr", "CG", "French (Congo - Brazzaville)", "FCFA", "XAF", "fra", "COG", null, null),
        "fr-CH" to IcuLocale("fr-CH", "fr", "CH", "French (Switzerland)", "CHF", "CHF", "fra", "CHE", null, null),
        "fr-CI" to IcuLocale("fr-CI", "fr", "CI", "French (Côte d’Ivoire)", "F CFA", "XOF", "fra", "CIV", null, null),
        "fr-CM" to IcuLocale("fr-CM", "fr", "CM", "French (Cameroon)", "FCFA", "XAF", "fra", "CMR", null, null),
        "fr-DJ" to IcuLocale("fr-DJ", "fr", "DJ", "French (Djibouti)", "Fdj", "DJF", "fra", "DJI", null, null),
        "fr-DZ" to IcuLocale("fr-DZ", "fr", "DZ", "French (Algeria)", "DA", "DZD", "fra", "DZA", null, null),
        "fr-FR" to IcuLocale("fr-FR", "fr", "FR", "French (France)", "€", "EUR", "fra", "FRA", null, null),
        "fr-GA" to IcuLocale("fr-GA", "fr", "GA", "French (Gabon)", "FCFA", "XAF", "fra", "GAB", null, null),
        "fr-GF" to IcuLocale("fr-GF", "fr", "GF", "French (French Guiana)", "€", "EUR", "fra", "GUF", null, null),
        "fr-GN" to IcuLocale("fr-GN", "fr", "GN", "French (Guinea)", "FG", "GNF", "fra", "GIN", null, null),
        "fr-GP" to IcuLocale("fr-GP", "fr", "GP", "French (Guadeloupe)", "€", "EUR", "fra", "GLP", null, null),
        "fr-GQ" to IcuLocale("fr-GQ", "fr", "GQ", "French (Equatorial Guinea)", "FCFA", "XAF", "fra", "GNQ", null, null),
        "fr-HT" to IcuLocale("fr-HT", "fr", "HT", "French (Haiti)", "G", "HTG", "fra", "HTI", null, null),
        "fr-KM" to IcuLocale("fr-KM", "fr", "KM", "French (Comoros)", "CF", "KMF", "fra", "COM", null, null),
        "fr-LU" to IcuLocale("fr-LU", "fr", "LU", "French (Luxembourg)", "€", "EUR", "fra", "LUX", null, null),
        "fr-MA" to IcuLocale("fr-MA", "fr", "MA", "French (Morocco)", "MAD", "MAD", "fra", "MAR", null, null),
        "fr-MC" to IcuLocale("fr-MC", "fr", "MC", "French (Monaco)", "€", "EUR", "fra", "MCO", null, null),
        "fr-MF" to IcuLocale("fr-MF", "fr", "MF", "French (St. Martin)", "€", "EUR", "fra", "MAF", null, null),
        "fr-MG" to IcuLocale("fr-MG", "fr", "MG", "French (Madagascar)", "Ar", "MGA", "fra", "MDG", null, null),
        "fr-ML" to IcuLocale("fr-ML", "fr", "ML", "French (Mali)", "F CFA", "XOF", "fra", "MLI", null, null),
        "fr-MQ" to IcuLocale("fr-MQ", "fr", "MQ", "French (Martinique)", "€", "EUR", "fra", "MTQ", null, null),
        "fr-MR" to IcuLocale("fr-MR", "fr", "MR", "French (Mauritania)", "UM", "MRU", "fra", "MRT", null, null),
        "fr-MU" to IcuLocale("fr-MU", "fr", "MU", "French (Mauritius)", "Rs", "MUR", "fra", "MUS", null, null),
        "fr-NC" to IcuLocale("fr-NC", "fr", "NC", "French (New Caledonia)", "FCFP", "XPF", "fra", "NCL", null, null),
        "fr-NE" to IcuLocale("fr-NE", "fr", "NE", "French (Niger)", "F CFA", "XOF", "fra", "NER", null, null),
        "fr-PF" to IcuLocale("fr-PF", "fr", "PF", "French (French Polynesia)", "FCFP", "XPF", "fra", "PYF", null, null),
        "fr-PM" to IcuLocale("fr-PM", "fr", "PM", "French (St. Pierre & Miquelon)", "€", "EUR", "fra", "SPM", null, null),
        "fr-RE" to IcuLocale("fr-RE", "fr", "RE", "French (Réunion)", "€", "EUR", "fra", "REU", null, null),
        "fr-RW" to IcuLocale("fr-RW", "fr", "RW", "French (Rwanda)", "RF", "RWF", "fra", "RWA", null, null),
        "fr-SC" to IcuLocale("fr-SC", "fr", "SC", "French (Seychelles)", "SR", "SCR", "fra", "SYC", null, null),
        "fr-SN" to IcuLocale("fr-SN", "fr", "SN", "French (Senegal)", "F CFA", "XOF", "fra", "SEN", null, null),
        "fr-SY" to IcuLocale("fr-SY", "fr", "SY", "French (Syria)", "LS", "SYP", "fra", "SYR", null, null),
        "fr-TD" to IcuLocale("fr-TD", "fr", "TD", "French (Chad)", "FCFA", "XAF", "fra", "TCD", null, null),
        "fr-TG" to IcuLocale("fr-TG", "fr", "TG", "French (Togo)", "F CFA", "XOF", "fra", "TGO", null, null),
        "fr-TN" to IcuLocale("fr-TN", "fr", "TN", "French (Tunisia)", "DT", "TND", "fra", "TUN", null, null),
        "fr-VU" to IcuLocale("fr-VU", "fr", "VU", "French (Vanuatu)", "VT", "VUV", "fra", "VUT", null, null),
        "fr-WF" to IcuLocale("fr-WF", "fr", "WF", "French (Wallis & Futuna)", "FCFP", "XPF", "fra", "WLF", null, null),
        "fr-YT" to IcuLocale("fr-YT", "fr", "YT", "French (Mayotte)", "€", "EUR", "fra", "MYT", null, null),
        "fur-IT" to IcuLocale("fur-IT", "fur", "IT", "Friulian (Italy)", "€", "EUR", "fur", "ITA", null, null),
        "fy-NL" to IcuLocale("fy-NL", "fy", "NL", "Western Frisian (Netherlands)", "€", "EUR", "fry", "NLD", null, null),
        "ga-GB" to IcuLocale("ga-GB", "ga", "GB", "Irish (United Kingdom)", "£", "GBP", "gle", "GBR", null, null),
        "ga-IE" to IcuLocale("ga-IE", "ga", "IE", "Irish (Ireland)", "€", "EUR", "gle", "IRL", null, null),
        "gd-GB" to IcuLocale("gd-GB", "gd", "GB", "Scottish Gaelic (United Kingdom)", "£", "GBP", "gla", "GBR", null, null),
        "gl-ES" to IcuLocale("gl-ES", "gl", "ES", "Galician (Spain)", "€", "EUR", "glg", "ESP", null, null),
        "gsw-CH" to IcuLocale("gsw-CH", "gsw", "CH", "Swiss German (Switzerland)", "CHF", "CHF", "gsw", "CHE", null, null),
        "gsw-FR" to IcuLocale("gsw-FR", "gsw", "FR", "Swiss German (France)", "€", "EUR", "gsw", "FRA", null, null),
        "gsw-LI" to IcuLocale("gsw-LI", "gsw", "LI", "Swiss German (Liechtenstein)", "CHF", "CHF", "gsw", "LIE", null, null),
        "gu-IN" to IcuLocale("gu-IN", "gu", "IN", "Gujarati (India)", "₹", "INR", "guj", "IND", null, null),
        "guz-KE" to IcuLocale("guz-KE", "guz", "KE", "Gusii (Kenya)", "Ksh", "KES", "guz", "KEN", null, null),
        "gv-IM" to IcuLocale("gv-IM", "gv", "IM", "Manx (Isle of Man)", "£", "GBP", "glv", "IMN", null, null),
        "ha-GH" to IcuLocale("ha-GH", "ha", "GH", "Hausa (Ghana)", "GH₵", "GHS", "hau", "GHA", null, null),
        "ha-NE" to IcuLocale("ha-NE", "ha", "NE", "Hausa (Niger)", "F CFA", "XOF", "hau", "NER", null, null),
        "ha-NG" to IcuLocale("ha-NG", "ha", "NG", "Hausa (Nigeria)", "₦", "NGN", "hau", "NGA", null, null),
        "haw-US" to IcuLocale("haw-US", "haw", "US", "Hawaiian (United States)", "$", "USD", "haw", "USA", null, null),
        "he-IL" to IcuLocale("he-IL", "he", "IL", "Hebrew (Israel)", "₪", "ILS", "heb", "ISR", null, null),
        "hi-IN" to IcuLocale("hi-IN", "hi", "IN", "Hindi (India)", "₹", "INR", "hin", "IND", null, null),
        "hi-Latn-IN" to IcuLocale("hi-Latn-IN", "hi", "IN", "Hindi (Latin, India)", "₹", "INR", "hin", "IND", "Latin", null),
        "hr-BA" to IcuLocale("hr-BA", "hr", "BA", "Croatian (Bosnia & Herzegovina)", "KM", "BAM", "hrv", "BIH", null, null),
        "hr-HR" to IcuLocale("hr-HR", "hr", "HR", "Croatian (Croatia)", "€", "EUR", "hrv", "HRV", null, null),
        "hsb-DE" to IcuLocale("hsb-DE", "hsb", "DE", "Upper Sorbian (Germany)", "€", "EUR", "hsb", "DEU", null, null),
        "hu-HU" to IcuLocale("hu-HU", "hu", "HU", "Hungarian (Hungary)", "Ft", "HUF", "hun", "HUN", null, null),
        "hy-AM" to IcuLocale("hy-AM", "hy", "AM", "Armenian (Armenia)", "֏", "AMD", "hye", "ARM", null, null),
        "ia-001" to IcuLocale("ia-001", "ia", "001", "Interlingua (world)", "¤", "XXX", "ina", "", null, null),
        "id-ID" to IcuLocale("id-ID", "id", "ID", "Indonesian (Indonesia)", "Rp", "IDR", "ind", "IDN", null, null),
        "ig-NG" to IcuLocale("ig-NG", "ig", "NG", "Igbo (Nigeria)", "₦", "NGN", "ibo", "NGA", null, null),
        "ii-CN" to IcuLocale("ii-CN", "ii", "CN", "Sichuan Yi (China)", "¥", "CNY", "iii", "CHN", null, null),
        "is-IS" to IcuLocale("is-IS", "is", "IS", "Icelandic (Iceland)", "kr.", "ISK", "isl", "ISL", null, null),
        "it-CH" to IcuLocale("it-CH", "it", "CH", "Italian (Switzerland)", "CHF", "CHF", "ita", "CHE", null, null),
        "it-IT" to IcuLocale("it-IT", "it", "IT", "Italian (Italy)", "€", "EUR", "ita", "ITA", null, null),
        "it-SM" to IcuLocale("it-SM", "it", "SM", "Italian (San Marino)", "€", "EUR", "ita", "SMR", null, null),
        "it-VA" to IcuLocale("it-VA", "it", "VA", "Italian (Vatican City)", "€", "EUR", "ita", "VAT", null, null),
        "ja-JP" to IcuLocale("ja-JP", "ja", "JP", "Japanese (Japan)", "￥", "JPY", "jpn", "JPN", null, null),
        "jgo-CM" to IcuLocale("jgo-CM", "jgo", "CM", "Ngomba (Cameroon)", "FCFA", "XAF", "jgo", "CMR", null, null),
        "jmc-TZ" to IcuLocale("jmc-TZ", "jmc", "TZ", "Machame (Tanzania)", "TSh", "TZS", "jmc", "TZA", null, null),
        "jv-ID" to IcuLocale("jv-ID", "jv", "ID", "Javanese (Indonesia)", "Rp", "IDR", "jav", "IDN", null, null),
        "ka-GE" to IcuLocale("ka-GE", "ka", "GE", "Georgian (Georgia)", "₾", "GEL", "kat", "GEO", null, null),
        "kab-DZ" to IcuLocale("kab-DZ", "kab", "DZ", "Kabyle (Algeria)", "DA", "DZD", "kab", "DZA", null, null),
        "kam-KE" to IcuLocale("kam-KE", "kam", "KE", "Kamba (Kenya)", "Ksh", "KES", "kam", "KEN", null, null),
        "kde-TZ" to IcuLocale("kde-TZ", "kde", "TZ", "Makonde (Tanzania)", "TSh", "TZS", "kde", "TZA", null, null),
        "kea-CV" to IcuLocale("kea-CV", "kea", "CV", "Kabuverdianu (Cape Verde)", "​", "CVE", "kea", "CPV", null, null),
        "kgp-BR" to IcuLocale("kgp-BR", "kgp", "BR", "Kaingang (Brazil)", "R$", "BRL", "", "BRA", null, null),
        "khq-ML" to IcuLocale("khq-ML", "khq", "ML", "Koyra Chiini (Mali)", "F CFA", "XOF", "khq", "MLI", null, null),
        "ki-KE" to IcuLocale("ki-KE", "ki", "KE", "Kikuyu (Kenya)", "Ksh", "KES", "kik", "KEN", null, null),
        "kk-KZ" to IcuLocale("kk-KZ", "kk", "KZ", "Kazakh (Kazakhstan)", "₸", "KZT", "kaz", "KAZ", null, null),
        "kkj-CM" to IcuLocale("kkj-CM", "kkj", "CM", "Kako (Cameroon)", "FCFA", "XAF", "kkj", "CMR", null, null),
        "kl-GL" to IcuLocale("kl-GL", "kl", "GL", "Kalaallisut (Greenland)", "kr.", "DKK", "kal", "GRL", null, null),
        "kln-KE" to IcuLocale("kln-KE", "kln", "KE", "Kalenjin (Kenya)", "Ksh", "KES", "kln", "KEN", null, null),
        "km-KH" to IcuLocale("km-KH", "km", "KH", "Khmer (Cambodia)", "៛", "KHR", "khm", "KHM", null, null),
        "kn-IN" to IcuLocale("kn-IN", "kn", "IN", "Kannada (India)", "₹", "INR", "kan", "IND", null, null),
        "ko-KP" to IcuLocale("ko-KP", "ko", "KP", "Korean (North Korea)", "KPW", "KPW", "kor", "PRK", null, null),
        "ko-KR" to IcuLocale("ko-KR", "ko", "KR", "Korean (South Korea)", "₩", "KRW", "kor", "KOR", null, null),
        "kok-IN" to IcuLocale("kok-IN", "kok", "IN", "Konkani (India)", "₹", "INR", "kok", "IND", null, null),
        "ks-Arab-IN" to IcuLocale("ks-Arab-IN", "ks", "IN", "Kashmiri (Arabic, India)", "₹", "INR", "kas", "IND", "Arabic", null),
        "ks-Deva-IN" to IcuLocale("ks-Deva-IN", "ks", "IN", "Kashmiri (Devanagari, India)", "₹", "INR", "kas", "IND", "Devanagari", null),
        "ksb-TZ" to IcuLocale("ksb-TZ", "ksb", "TZ", "Shambala (Tanzania)", "TSh", "TZS", "ksb", "TZA", null, null),
        "ksf-CM" to IcuLocale("ksf-CM", "ksf", "CM", "Bafia (Cameroon)", "FCFA", "XAF", "ksf", "CMR", null, null),
        "ksh-DE" to IcuLocale("ksh-DE", "ksh", "DE", "Colognian (Germany)", "€", "EUR", "ksh", "DEU", null, null),
        "ku-TR" to IcuLocale("ku-TR", "ku", "TR", "Kurdish (Turkey)", "₺", "TRY", "kur", "TUR", null, null),
        "kw-GB" to IcuLocale("kw-GB", "kw", "GB", "Cornish (United Kingdom)", "£", "GBP", "cor", "GBR", null, null),
        "ky-KG" to IcuLocale("ky-KG", "ky", "KG", "Kyrgyz (Kyrgyzstan)", "сом", "KGS", "kir", "KGZ", null, null),
        "lag-TZ" to IcuLocale("lag-TZ", "lag", "TZ", "Langi (Tanzania)", "TSh", "TZS", "lag", "TZA", null, null),
        "lb-LU" to IcuLocale("lb-LU", "lb", "LU", "Luxembourgish (Luxembourg)", "€", "EUR", "ltz", "LUX", null, null),
        "lg-UG" to IcuLocale("lg-UG", "lg", "UG", "Ganda (Uganda)", "USh", "UGX", "lug", "UGA", null, null),
        "lkt-US" to IcuLocale("lkt-US", "lkt", "US", "Lakota (United States)", "$", "USD", "lkt", "USA", null, null),
        "ln-AO" to IcuLocale("ln-AO", "ln", "AO", "Lingala (Angola)", "Kz", "AOA", "lin", "AGO", null, null),
        "ln-CD" to IcuLocale("ln-CD", "ln", "CD", "Lingala (Congo - Kinshasa)", "FC", "CDF", "lin", "COD", null, null),
        "ln-CF" to IcuLocale("ln-CF", "ln", "CF", "Lingala (Central African Republic)", "FCFA", "XAF", "lin", "CAF", null, null),
        "ln-CG" to IcuLocale("ln-CG", "ln", "CG", "Lingala (Congo - Brazzaville)", "FCFA", "XAF", "lin", "COG", null, null),
        "lo-LA" to IcuLocale("lo-LA", "lo", "LA", "Lao (Laos)", "₭", "LAK", "lao", "LAO", null, null),
        "lrc-IQ" to IcuLocale("lrc-IQ", "lrc", "IQ", "Northern Luri (Iraq)", "د.ع.‏", "IQD", "", "IRQ", null, null),
        "lrc-IR" to IcuLocale("lrc-IR", "lrc", "IR", "Northern Luri (Iran)", "IRR", "IRR", "", "IRN", null, null),
        "lt-LT" to IcuLocale("lt-LT", "lt", "LT", "Lithuanian (Lithuania)", "€", "EUR", "lit", "LTU", null, null),
        "lu-CD" to IcuLocale("lu-CD", "lu", "CD", "Luba-Katanga (Congo - Kinshasa)", "FC", "CDF", "lub", "COD", null, null),
        "luo-KE" to IcuLocale("luo-KE", "luo", "KE", "Luo (Kenya)", "Ksh", "KES", "luo", "KEN", null, null),
        "luy-KE" to IcuLocale("luy-KE", "luy", "KE", "Luyia (Kenya)", "Ksh", "KES", "luy", "KEN", null, null),
        "lv-LV" to IcuLocale("lv-LV", "lv", "LV", "Latvian (Latvia)", "€", "EUR", "lav", "LVA", null, null),
        "mai-IN" to IcuLocale("mai-IN", "mai", "IN", "Maithili (India)", "₹", "INR", "mai", "IND", null, null),
        "mas-KE" to IcuLocale("mas-KE", "mas", "KE", "Masai (Kenya)", "Ksh", "KES", "mas", "KEN", null, null),
        "mas-TZ" to IcuLocale("mas-TZ", "mas", "TZ", "Masai (Tanzania)", "TSh", "TZS", "mas", "TZA", null, null),
        "mer-KE" to IcuLocale("mer-KE", "mer", "KE", "Meru (Kenya)", "Ksh", "KES", "mer", "KEN", null, null),
        "mfe-MU" to IcuLocale("mfe-MU", "mfe", "MU", "Morisyen (Mauritius)", "Rs", "MUR", "mfe", "MUS", null, null),
        "mg-MG" to IcuLocale("mg-MG", "mg", "MG", "Malagasy (Madagascar)", "Ar", "MGA", "mlg", "MDG", null, null),
        "mgh-MZ" to IcuLocale("mgh-MZ", "mgh", "MZ", "Makhuwa-Meetto (Mozambique)", "MTn", "MZN", "mgh", "MOZ", null, null),
        "mgo-CM" to IcuLocale("mgo-CM", "mgo", "CM", "Metaʼ (Cameroon)", "FCFA", "XAF", "mgo", "CMR", null, null),
        "mi-NZ" to IcuLocale("mi-NZ", "mi", "NZ", "Māori (New Zealand)", "$", "NZD", "mri", "NZL", null, null),
        "mk-MK" to IcuLocale("mk-MK", "mk", "MK", "Macedonian (North Macedonia)", "ден.", "MKD", "mkd", "MKD", null, null),
        "ml-IN" to IcuLocale("ml-IN", "ml", "IN", "Malayalam (India)", "₹", "INR", "mal", "IND", null, null),
        "mn-MN" to IcuLocale("mn-MN", "mn", "MN", "Mongolian (Mongolia)", "₮", "MNT", "mon", "MNG", null, null),
        "mni-Beng-IN" to IcuLocale("mni-Beng-IN", "mni", "IN", "Manipuri (Bangla, India)", "₹", "INR", "mni", "IND", "Bangla", null),
        "mr-IN" to IcuLocale("mr-IN", "mr", "IN", "Marathi (India)", "₹", "INR", "mar", "IND", null, null),
        "ms-BN" to IcuLocale("ms-BN", "ms", "BN", "Malay (Brunei)", "$", "BND", "msa", "BRN", null, null),
        "ms-ID" to IcuLocale("ms-ID", "ms", "ID", "Malay (Indonesia)", "Rp", "IDR", "msa", "IDN", null, null),
        "ms-MY" to IcuLocale("ms-MY", "ms", "MY", "Malay (Malaysia)", "RM", "MYR", "msa", "MYS", null, null),
        "ms-SG" to IcuLocale("ms-SG", "ms", "SG", "Malay (Singapore)", "$", "SGD", "msa", "SGP", null, null),
        "mt-MT" to IcuLocale("mt-MT", "mt", "MT", "Maltese (Malta)", "€", "EUR", "mlt", "MLT", null, null),
        "mua-CM" to IcuLocale("mua-CM", "mua", "CM", "Mundang (Cameroon)", "FCFA", "XAF", "mua", "CMR", null, null),
        "my-MM" to IcuLocale("my-MM", "my", "MM", "Burmese (Myanmar [Burma])", "K", "MMK", "mya", "MMR", null, null),
        "mzn-IR" to IcuLocale("mzn-IR", "mzn", "IR", "Mazanderani (Iran)", "IRR", "IRR", "", "IRN", null, null),
        "naq-NA" to IcuLocale("naq-NA", "naq", "NA", "Nama (Namibia)", "$", "NAD", "naq", "NAM", null, null),
        "nb-NO" to IcuLocale("nb-NO", "nb", "NO", "Norwegian Bokmål (Norway)", "kr", "NOK", "nob", "NOR", null, null),
        "nb-SJ" to IcuLocale("nb-SJ", "nb", "SJ", "Norwegian Bokmål (Svalbard & Jan Mayen)", "kr", "NOK", "nob", "SJM", null, null),
        "nd-ZW" to IcuLocale("nd-ZW", "nd", "ZW", "North Ndebele (Zimbabwe)", "US$", "USD", "nde", "ZWE", null, null),
        "ne-IN" to IcuLocale("ne-IN", "ne", "IN", "Nepali (India)", "₹", "INR", "nep", "IND", null, null),
        "ne-NP" to IcuLocale("ne-NP", "ne", "NP", "Nepali (Nepal)", "नेरू", "NPR", "nep", "NPL", null, null),
        "nl-AW" to IcuLocale("nl-AW", "nl", "AW", "Dutch (Aruba)", "Afl.", "AWG", "nld", "ABW", null, null),
        "nl-BE" to IcuLocale("nl-BE", "nl", "BE", "Dutch (Belgium)", "€", "EUR", "nld", "BEL", null, null),
        "nl-BQ" to IcuLocale("nl-BQ", "nl", "BQ", "Dutch (Caribbean Netherlands)", "$", "USD", "nld", "BES", null, null),
        "nl-CW" to IcuLocale("nl-CW", "nl", "CW", "Dutch (Curaçao)", "NAf.", "ANG", "nld", "CUW", null, null),
        "nl-NL" to IcuLocale("nl-NL", "nl", "NL", "Dutch (Netherlands)", "€", "EUR", "nld", "NLD", null, null),
        "nl-SR" to IcuLocale("nl-SR", "nl", "SR", "Dutch (Suriname)", "$", "SRD", "nld", "SUR", null, null),
        "nl-SX" to IcuLocale("nl-SX", "nl", "SX", "Dutch (Sint Maarten)", "NAf.", "ANG", "nld", "SXM", null, null),
        "nmg-CM" to IcuLocale("nmg-CM", "nmg", "CM", "Kwasio (Cameroon)", "FCFA", "XAF", "nmg", "CMR", null, null),
        "nn-NO" to IcuLocale("nn-NO", "nn", "NO", "Norwegian Nynorsk (Norway)", "kr", "NOK", "nno", "NOR", null, null),
        "nnh-CM" to IcuLocale("nnh-CM", "nnh", "CM", "Ngiemboon (Cameroon)", "FCFA", "XAF", "nnh", "CMR", null, null),
        "nus-SS" to IcuLocale("nus-SS", "nus", "SS", "Nuer (South Sudan)", "£", "SSP", "nus", "SSD", null, null),
        "nyn-UG" to IcuLocale("nyn-UG", "nyn", "UG", "Nyankole (Uganda)", "USh", "UGX", "nyn", "UGA", null, null),
        "om-ET" to IcuLocale("om-ET", "om", "ET", "Oromo (Ethiopia)", "Br", "ETB", "orm", "ETH", null, null),
        "om-KE" to IcuLocale("om-KE", "om", "KE", "Oromo (Kenya)", "Ksh", "KES", "orm", "KEN", null, null),
        "or-IN" to IcuLocale("or-IN", "or", "IN", "Odia (India)", "₹", "INR", "ori", "IND", null, null),
        "os-GE" to IcuLocale("os-GE", "os", "GE", "Ossetic (Georgia)", "₾", "GEL", "oss", "GEO", null, null),
        "os-RU" to IcuLocale("os-RU", "os", "RU", "Ossetic (Russia)", "₽", "RUB", "oss", "RUS", null, null),
        "pa-Arab-PK" to IcuLocale("pa-Arab-PK", "pa", "PK", "Punjabi (Arabic, Pakistan)", "ر", "PKR", "pan", "PAK", "Arabic", null),
        "pa-Guru-IN" to IcuLocale("pa-Guru-IN", "pa", "IN", "Punjabi (Gurmukhi, India)", "₹", "INR", "pan", "IND", "Gurmukhi", null),
        "pcm-NG" to IcuLocale("pcm-NG", "pcm", "NG", "Nigerian Pidgin (Nigeria)", "₦", "NGN", "", "NGA", null, null),
        "pl-PL" to IcuLocale("pl-PL", "pl", "PL", "Polish (Poland)", "zł", "PLN", "pol", "POL", null, null),
        "ps-AF" to IcuLocale("ps-AF", "ps", "AF", "Pashto (Afghanistan)", "؋", "AFN", "pus", "AFG", null, null),
        "ps-PK" to IcuLocale("ps-PK", "ps", "PK", "Pashto (Pakistan)", "Rs", "PKR", "pus", "PAK", null, null),
        "pt-AO" to IcuLocale("pt-AO", "pt", "AO", "Portuguese (Angola)", "Kz", "AOA", "por", "AGO", null, null),
        "pt-BR" to IcuLocale("pt-BR", "pt", "BR", "Portuguese (Brazil)", "R$", "BRL", "por", "BRA", null, null),
        "pt-CH" to IcuLocale("pt-CH", "pt", "CH", "Portuguese (Switzerland)", "CHF", "CHF", "por", "CHE", null, null),
        "pt-CV" to IcuLocale("pt-CV", "pt", "CV", "Portuguese (Cape Verde)", "​", "CVE", "por", "CPV", null, null),
        "pt-GQ" to IcuLocale("pt-GQ", "pt", "GQ", "Portuguese (Equatorial Guinea)", "FCFA", "XAF", "por", "GNQ", null, null),
        "pt-GW" to IcuLocale("pt-GW", "pt", "GW", "Portuguese (Guinea-Bissau)", "F CFA", "XOF", "por", "GNB", null, null),
        "pt-LU" to IcuLocale("pt-LU", "pt", "LU", "Portuguese (Luxembourg)", "€", "EUR", "por", "LUX", null, null),
        "pt-MO" to IcuLocale("pt-MO", "pt", "MO", "Portuguese (Macao SAR China)", "MOP$", "MOP", "por", "MAC", null, null),
        "pt-MZ" to IcuLocale("pt-MZ", "pt", "MZ", "Portuguese (Mozambique)", "MTn", "MZN", "por", "MOZ", null, null),
        "pt-PT" to IcuLocale("pt-PT", "pt", "PT", "Portuguese (Portugal)", "€", "EUR", "por", "PRT", null, null),
        "pt-ST" to IcuLocale("pt-ST", "pt", "ST", "Portuguese (São Tomé & Príncipe)", "Db", "STN", "por", "STP", null, null),
        "pt-TL" to IcuLocale("pt-TL", "pt", "TL", "Portuguese (Timor-Leste)", "US$", "USD", "por", "TLS", null, null),
        "qu-BO" to IcuLocale("qu-BO", "qu", "BO", "Quechua (Bolivia)", "Bs", "BOB", "que", "BOL", null, null),
        "qu-EC" to IcuLocale("qu-EC", "qu", "EC", "Quechua (Ecuador)", "$", "USD", "que", "ECU", null, null),
        "qu-PE" to IcuLocale("qu-PE", "qu", "PE", "Quechua (Peru)", "S/", "PEN", "que", "PER", null, null),
        "raj-IN" to IcuLocale("raj-IN", "raj", "IN", "Rajasthani (India)", "₹", "INR", "raj", "IND", null, null),
        "rm-CH" to IcuLocale("rm-CH", "rm", "CH", "Romansh (Switzerland)", "CHF", "CHF", "roh", "CHE", null, null),
        "rn-BI" to IcuLocale("rn-BI", "rn", "BI", "Rundi (Burundi)", "FBu", "BIF", "run", "BDI", null, null),
        "ro-MD" to IcuLocale("ro-MD", "ro", "MD", "Romanian (Moldova)", "L", "MDL", "ron", "MDA", null, null),
        "ro-RO" to IcuLocale("ro-RO", "ro", "RO", "Romanian (Romania)", "RON", "RON", "ron", "ROU", null, null),
        "rof-TZ" to IcuLocale("rof-TZ", "rof", "TZ", "Rombo (Tanzania)", "TSh", "TZS", "rof", "TZA", null, null),
        "ru-BY" to IcuLocale("ru-BY", "ru", "BY", "Russian (Belarus)", "Br", "BYN", "rus", "BLR", null, null),
        "ru-KG" to IcuLocale("ru-KG", "ru", "KG", "Russian (Kyrgyzstan)", "сом", "KGS", "rus", "KGZ", null, null),
        "ru-KZ" to IcuLocale("ru-KZ", "ru", "KZ", "Russian (Kazakhstan)", "₸", "KZT", "rus", "KAZ", null, null),
        "ru-MD" to IcuLocale("ru-MD", "ru", "MD", "Russian (Moldova)", "L", "MDL", "rus", "MDA", null, null),
        "ru-RU" to IcuLocale("ru-RU", "ru", "RU", "Russian (Russia)", "₽", "RUB", "rus", "RUS", null, null),
        "ru-UA" to IcuLocale("ru-UA", "ru", "UA", "Russian (Ukraine)", "₴", "UAH", "rus", "UKR", null, null),
        "rw-RW" to IcuLocale("rw-RW", "rw", "RW", "Kinyarwanda (Rwanda)", "RF", "RWF", "kin", "RWA", null, null),
        "rwk-TZ" to IcuLocale("rwk-TZ", "rwk", "TZ", "Rwa (Tanzania)", "TSh", "TZS", "rwk", "TZA", null, null),
        "sa-IN" to IcuLocale("sa-IN", "sa", "IN", "Sanskrit (India)", "₹", "INR", "san", "IND", null, null),
        "sah-RU" to IcuLocale("sah-RU", "sah", "RU", "Yakut (Russia)", "₽", "RUB", "sah", "RUS", null, null),
        "saq-KE" to IcuLocale("saq-KE", "saq", "KE", "Samburu (Kenya)", "Ksh", "KES", "saq", "KEN", null, null),
        "sat-Olck-IN" to IcuLocale("sat-Olck-IN", "sat", "IN", "Santali (Ol Chiki, India)", "₹", "INR", "sat", "IND", "Ol Chiki", null),
        "sbp-TZ" to IcuLocale("sbp-TZ", "sbp", "TZ", "Sangu (Tanzania)", "TSh", "TZS", "sbp", "TZA", null, null),
        "sc-IT" to IcuLocale("sc-IT", "sc", "IT", "Sardinian (Italy)", "€", "EUR", "srd", "ITA", null, null),
        "sd-Arab-PK" to IcuLocale("sd-Arab-PK", "sd", "PK", "Sindhi (Arabic, Pakistan)", "Rs", "PKR", "snd", "PAK", "Arabic", null),
        "sd-Deva-IN" to IcuLocale("sd-Deva-IN", "sd", "IN", "Sindhi (Devanagari, India)", "₹", "INR", "snd", "IND", "Devanagari", null),
        "se-FI" to IcuLocale("se-FI", "se", "FI", "Northern Sami (Finland)", "€", "EUR", "sme", "FIN", null, null),
        "se-NO" to IcuLocale("se-NO", "se", "NO", "Northern Sami (Norway)", "kr", "NOK", "sme", "NOR", null, null),
        "se-SE" to IcuLocale("se-SE", "se", "SE", "Northern Sami (Sweden)", "kr", "SEK", "sme", "SWE", null, null),
        "seh-MZ" to IcuLocale("seh-MZ", "seh", "MZ", "Sena (Mozambique)", "MTn", "MZN", "seh", "MOZ", null, null),
        "ses-ML" to IcuLocale("ses-ML", "ses", "ML", "Koyraboro Senni (Mali)", "F CFA", "XOF", "ses", "MLI", null, null),
        "sg-CF" to IcuLocale("sg-CF", "sg", "CF", "Sango (Central African Republic)", "FCFA", "XAF", "sag", "CAF", null, null),
        "shi-Latn-MA" to IcuLocale("shi-Latn-MA", "shi", "MA", "Tachelhit (Latin, Morocco)", "MAD", "MAD", "shi", "MAR", "Latin", null),
        "shi-Tfng-MA" to IcuLocale("shi-Tfng-MA", "shi", "MA", "Tachelhit (Tifinagh, Morocco)", "MAD", "MAD", "shi", "MAR", "Tifinagh", null),
        "si-LK" to IcuLocale("si-LK", "si", "LK", "Sinhala (Sri Lanka)", "රු.", "LKR", "sin", "LKA", null, null),
        "sk-SK" to IcuLocale("sk-SK", "sk", "SK", "Slovak (Slovakia)", "€", "EUR", "slk", "SVK", null, null),
        "sl-SI" to IcuLocale("sl-SI", "sl", "SI", "Slovenian (Slovenia)", "€", "EUR", "slv", "SVN", null, null),
        "smn-FI" to IcuLocale("smn-FI", "smn", "FI", "Inari Sami (Finland)", "€", "EUR", "smn", "FIN", null, null),
        "sn-ZW" to IcuLocale("sn-ZW", "sn", "ZW", "Shona (Zimbabwe)", "US$", "USD", "sna", "ZWE", null, null),
        "so-DJ" to IcuLocale("so-DJ", "so", "DJ", "Somali (Djibouti)", "Fdj", "DJF", "som", "DJI", null, null),
        "so-ET" to IcuLocale("so-ET", "so", "ET", "Somali (Ethiopia)", "Br", "ETB", "som", "ETH", null, null),
        "so-KE" to IcuLocale("so-KE", "so", "KE", "Somali (Kenya)", "Ksh", "KES", "som", "KEN", null, null),
        "so-SO" to IcuLocale("so-SO", "so", "SO", "Somali (Somalia)", "S", "SOS", "som", "SOM", null, null),
        "sq-AL" to IcuLocale("sq-AL", "sq", "AL", "Albanian (Albania)", "Lekë", "ALL", "sqi", "ALB", null, null),
        "sq-MK" to IcuLocale("sq-MK", "sq", "MK", "Albanian (North Macedonia)", "den", "MKD", "sqi", "MKD", null, null),
        "sq-XK" to IcuLocale("sq-XK", "sq", "XK", "Albanian (Kosovo)", "€", "EUR", "sqi", "XKK", null, null),
        "sr-Cyrl-BA" to IcuLocale("sr-Cyrl-BA", "sr", "BA", "Serbian (Cyrillic, Bosnia & Herzegovina)", "КМ", "BAM", "srp", "BIH", "Cyrillic", null),
        "sr-Cyrl-ME" to IcuLocale("sr-Cyrl-ME", "sr", "ME", "Serbian (Cyrillic, Montenegro)", "€", "EUR", "srp", "MNE", "Cyrillic", null),
        "sr-Cyrl-RS" to IcuLocale("sr-Cyrl-RS", "sr", "RS", "Serbian (Cyrillic, Serbia)", "RSD", "RSD", "srp", "SRB", "Cyrillic", null),
        "sr-Cyrl-XK" to IcuLocale("sr-Cyrl-XK", "sr", "XK", "Serbian (Cyrillic, Kosovo)", "€", "EUR", "srp", "XKK", "Cyrillic", null),
        "sr-Latn-BA" to IcuLocale("sr-Latn-BA", "sr", "BA", "Serbian (Latin, Bosnia & Herzegovina)", "KM", "BAM", "srp", "BIH", "Latin", null),
        "sr-Latn-ME" to IcuLocale("sr-Latn-ME", "sr", "ME", "Serbian (Latin, Montenegro)", "€", "EUR", "srp", "MNE", "Latin", null),
        "sr-Latn-RS" to IcuLocale("sr-Latn-RS", "sr", "RS", "Serbian (Latin, Serbia)", "RSD", "RSD", "srp", "SRB", "Latin", null),
        "sr-Latn-XK" to IcuLocale("sr-Latn-XK", "sr", "XK", "Serbian (Latin, Kosovo)", "€", "EUR", "srp", "XKK", "Latin", null),
        "su-Latn-ID" to IcuLocale("su-Latn-ID", "su", "ID", "Sundanese (Latin, Indonesia)", "Rp", "IDR", "sun", "IDN", "Latin", null),
        "sv-AX" to IcuLocale("sv-AX", "sv", "AX", "Swedish (Åland Islands)", "€", "EUR", "swe", "ALA", null, null),
        "sv-FI" to IcuLocale("sv-FI", "sv", "FI", "Swedish (Finland)", "€", "EUR", "swe", "FIN", null, null),
        "sv-SE" to IcuLocale("sv-SE", "sv", "SE", "Swedish (Sweden)", "kr", "SEK", "swe", "SWE", null, null),
        "sw-CD" to IcuLocale("sw-CD", "sw", "CD", "Swahili (Congo - Kinshasa)", "FC", "CDF", "swa", "COD", null, null),
        "sw-KE" to IcuLocale("sw-KE", "sw", "KE", "Swahili (Kenya)", "Ksh", "KES", "swa", "KEN", null, null),
        "sw-TZ" to IcuLocale("sw-TZ", "sw", "TZ", "Swahili (Tanzania)", "TSh", "TZS", "swa", "TZA", null, null),
        "sw-UG" to IcuLocale("sw-UG", "sw", "UG", "Swahili (Uganda)", "USh", "UGX", "swa", "UGA", null, null),
        "ta-IN" to IcuLocale("ta-IN", "ta", "IN", "Tamil (India)", "₹", "INR", "tam", "IND", null, null),
        "ta-LK" to IcuLocale("ta-LK", "ta", "LK", "Tamil (Sri Lanka)", "Rs.", "LKR", "tam", "LKA", null, null),
        "ta-MY" to IcuLocale("ta-MY", "ta", "MY", "Tamil (Malaysia)", "RM", "MYR", "tam", "MYS", null, null),
        "ta-SG" to IcuLocale("ta-SG", "ta", "SG", "Tamil (Singapore)", "$", "SGD", "tam", "SGP", null, null),
        "te-IN" to IcuLocale("te-IN", "te", "IN", "Telugu (India)", "₹", "INR", "tel", "IND", null, null),
        "teo-KE" to IcuLocale("teo-KE", "teo", "KE", "Teso (Kenya)", "Ksh", "KES", "teo", "KEN", null, null),
        "teo-UG" to IcuLocale("teo-UG", "teo", "UG", "Teso (Uganda)", "USh", "UGX", "teo", "UGA", null, null),
        "tg-TJ" to IcuLocale("tg-TJ", "tg", "TJ", "Tajik (Tajikistan)", "сом.", "TJS", "tgk", "TJK", null, null),
        "th-TH" to IcuLocale("th-TH", "th", "TH", "Thai (Thailand)", "฿", "THB", "tha", "THA", null, null),
        "ti-ER" to IcuLocale("ti-ER", "ti", "ER", "Tigrinya (Eritrea)", "Nfk", "ERN", "tir", "ERI", null, null),
        "ti-ET" to IcuLocale("ti-ET", "ti", "ET", "Tigrinya (Ethiopia)", "Br", "ETB", "tir", "ETH", null, null),
        "tk-TM" to IcuLocale("tk-TM", "tk", "TM", "Turkmen (Turkmenistan)", "TMT", "TMT", "tuk", "TKM", null, null),
        "to-TO" to IcuLocale("to-TO", "to", "TO", "Tongan (Tonga)", "T$", "TOP", "ton", "TON", null, null),
        "tr-CY" to IcuLocale("tr-CY", "tr", "CY", "Turkish (Cyprus)", "€", "EUR", "tur", "CYP", null, null),
        "tr-TR" to IcuLocale("tr-TR", "tr", "TR", "Turkish (Turkey)", "₺", "TRY", "tur", "TUR", null, null),
        "tt-RU" to IcuLocale("tt-RU", "tt", "RU", "Tatar (Russia)", "₽", "RUB", "tat", "RUS", null, null),
        "twq-NE" to IcuLocale("twq-NE", "twq", "NE", "Tasawaq (Niger)", "F CFA", "XOF", "twq", "NER", null, null),
        "tzm-MA" to IcuLocale("tzm-MA", "tzm", "MA", "Central Atlas Tamazight (Morocco)", "MAD", "MAD", "tzm", "MAR", null, null),
        "ug-CN" to IcuLocale("ug-CN", "ug", "CN", "Uyghur (China)", "￥", "CNY", "uig", "CHN", null, null),
        "uk-UA" to IcuLocale("uk-UA", "uk", "UA", "Ukrainian (Ukraine)", "₴", "UAH", "ukr", "UKR", null, null),
        "ur-IN" to IcuLocale("ur-IN", "ur", "IN", "Urdu (India)", "₹", "INR", "urd", "IND", null, null),
        "ur-PK" to IcuLocale("ur-PK", "ur", "PK", "Urdu (Pakistan)", "Rs", "PKR", "urd", "PAK", null, null),
        "uz-Arab-AF" to IcuLocale("uz-Arab-AF", "uz", "AF", "Uzbek (Arabic, Afghanistan)", "؋", "AFN", "uzb", "AFG", "Arabic", null),
        "uz-Cyrl-UZ" to IcuLocale("uz-Cyrl-UZ", "uz", "UZ", "Uzbek (Cyrillic, Uzbekistan)", "сўм", "UZS", "uzb", "UZB", "Cyrillic", null),
        "uz-Latn-UZ" to IcuLocale("uz-Latn-UZ", "uz", "UZ", "Uzbek (Latin, Uzbekistan)", "soʻm", "UZS", "uzb", "UZB", "Latin", null),
        "vai-Latn-LR" to IcuLocale("vai-Latn-LR", "vai", "LR", "Vai (Latin, Liberia)", "$", "LRD", "vai", "LBR", "Latin", null),
        "vai-Vaii-LR" to IcuLocale("vai-Vaii-LR", "vai", "LR", "Vai (Vai, Liberia)", "$", "LRD", "vai", "LBR", "Vai", null),
        "vi-VN" to IcuLocale("vi-VN", "vi", "VN", "Vietnamese (Vietnam)", "₫", "VND", "vie", "VNM", null, null),
        "vun-TZ" to IcuLocale("vun-TZ", "vun", "TZ", "Vunjo (Tanzania)", "TSh", "TZS", "vun", "TZA", null, null),
        "wae-CH" to IcuLocale("wae-CH", "wae", "CH", "Walser (Switzerland)", "CHF", "CHF", "wae", "CHE", null, null),
        "wo-SN" to IcuLocale("wo-SN", "wo", "SN", "Wolof (Senegal)", "F CFA", "XOF", "wol", "SEN", null, null),
        "xh-ZA" to IcuLocale("xh-ZA", "xh", "ZA", "Xhosa (South Africa)", "R", "ZAR", "xho", "ZAF", null, null),
        "xog-UG" to IcuLocale("xog-UG", "xog", "UG", "Soga (Uganda)", "USh", "UGX", "xog", "UGA", null, null),
        "yav-CM" to IcuLocale("yav-CM", "yav", "CM", "Yangben (Cameroon)", "FCFA", "XAF", "yav", "CMR", null, null),
        "yi-001" to IcuLocale("yi-001", "yi", "001", "Yiddish (world)", "¤", "XXX", "yid", "", null, null),
        "yo-BJ" to IcuLocale("yo-BJ", "yo", "BJ", "Yoruba (Benin)", "F CFA", "XOF", "yor", "BEN", null, null),
        "yo-NG" to IcuLocale("yo-NG", "yo", "NG", "Yoruba (Nigeria)", "₦", "NGN", "yor", "NGA", null, null),
        "yrl-BR" to IcuLocale("yrl-BR", "yrl", "BR", "Nheengatu (Brazil)", "R$", "BRL", "", "BRA", null, null),
        "yrl-CO" to IcuLocale("yrl-CO", "yrl", "CO", "Nheengatu (Colombia)", "$", "COP", "", "COL", null, null),
        "yrl-VE" to IcuLocale("yrl-VE", "yrl", "VE", "Nheengatu (Venezuela)", "Bs.S", "VES", "", "VEN", null, null),
        "yue-Hans-CN" to IcuLocale("yue-Hans-CN", "yue", "CN", "Cantonese (Simplified, China)", "￥", "CNY", "yue", "CHN", "Simplified Han", null),
        "yue-Hant-HK" to IcuLocale("yue-Hant-HK", "yue", "HK", "Cantonese (Traditional, Hong Kong SAR China)", "HK$", "HKD", "yue", "HKG", "Traditional Han", null),
        "zgh-MA" to IcuLocale("zgh-MA", "zgh", "MA", "Standard Moroccan Tamazight (Morocco)", "MAD", "MAD", "", "MAR", null, null),
        "zh-Hans-CN" to IcuLocale("zh-Hans-CN", "zh", "CN", "Chinese (Simplified, China)", "¥", "CNY", "zho", "CHN", "Simplified Han", null),
        "zh-Hans-HK" to IcuLocale("zh-Hans-HK", "zh", "HK", "Chinese (Simplified, Hong Kong SAR China)", "HK$", "HKD", "zho", "HKG", "Simplified Han", null),
        "zh-Hans-MO" to IcuLocale("zh-Hans-MO", "zh", "MO", "Chinese (Simplified, Macao SAR China)", "MOP$", "MOP", "zho", "MAC", "Simplified Han", null),
        "zh-Hans-SG" to IcuLocale("zh-Hans-SG", "zh", "SG", "Chinese (Simplified, Singapore)", "$", "SGD", "zho", "SGP", "Simplified Han", null),
        "zh-Hant-HK" to IcuLocale("zh-Hant-HK", "zh", "HK", "Chinese (Traditional, Hong Kong SAR China)", "HK$", "HKD", "zho", "HKG", "Traditional Han", null),
        "zh-Hant-MO" to IcuLocale("zh-Hant-MO", "zh", "MO", "Chinese (Traditional, Macao SAR China)", "MOP$", "MOP", "zho", "MAC", "Traditional Han", null),
        "zh-Hant-TW" to IcuLocale("zh-Hant-TW", "zh", "TW", "Chinese (Traditional, Taiwan)", "$", "TWD", "zho", "TWN", "Traditional Han", null),
        "zu-ZA" to IcuLocale("zu-ZA", "zu", "ZA", "Zulu (South Africa)", "R", "ZAR", "zul", "ZAF", null, null)
    )


    fun currencyIsoCodeForLocale(language: String, country: String): String? =
        LocaleToCurrencyIsoCode[Locale.languageTagFor(language, country)]

    data class IcuLocale(
        val languageTag: String,
        val language: String,
        val country: String,
        val displayName: String,
        val currencySymbol: String,
        val isoCurrencyCode: String,
        val iso3Language: String,
        val iso3Country: String,
        val script: String? = null,
        val variant: String? = null
    )
}